// list of questions for the quiz. Dictionary with multiple sets of questions

export const questionSet = [
    {
        title: 'Standard',
        questions: [ 
        'Physiker',
        'Stadt in Deutschland',
        'Macht Spaß',
        'Maler',
        'Europäisches Land',
        'Lieblingssport',
        'Schauspieler',
        'Komponist',
        'Tier mit vier Beinen',
        'Bekanntes Buch',
        'Leckeres Dessert',
        'Fußballverein',
        'Filmregisseur',
        'Musikinstrument',
        'Hauptstadt eines Landes',
        'Wissenschaftler',
        'Schauspielerin',
        'Politiker',
        'Hobbies in der Freizeit',
        'Bekanntes Gemälde',
        'Bekanntes Modelabel',
        'Entdecker',
        'Schriftsteller',
        'Bekanntes Monument',
        'Sänger',
        'Filmfigur',
        'Lieblingsfilmgenre',
        'Bauwerk',
        'Fernsehserie',
        'Athlet',
        'Zitat',
        'Persönlichkeit aus der Geschichte',
        'Lieblingsmusikgenre',
        'Modedesigner',
        'Oper',
        'Astronaut',
        'Schauspielerin',
        'Roman',
        'Lieblingsurlaubsziel',
        'Dichter',
        'Dirigent',
        'Sportveranstaltung',
        'Schauspielerin',
        'Theaterstück',
        'Computerspiel',
        'Naturwissenschaft',
        'Bekanntes Sportteam',
        'Fotograf',
        'Redewendung',
        'Bekanntes Museum',
        'Lieblingsrestaurant',
        'historische Periode'
    ],
    },
    {
        title: 'Oh no',
        questions: ['Kein Auto', 'Kein Haus', 'Kein Baum', 'Kein Hund'],

    },
]