import type {Language} from '../i18n/LocalizationContext';

export type QuestionPack = {
  id: string;
  title: string;
  questions: string[];
  custom?: boolean;
};

type LocalizedPack = {
  id: string;
  title: Record<Language, string>;
  questions: Record<Language, string[]>;
};

// Every built-in pack follows the same bilingual schema and stable ID.
const localizedPacks: LocalizedPack[] = [
  {
    id: 'standard',
    title: {
      de: 'Standard',
      en: 'Standard',
    },
    questions: {
      de: [
        'Serie',
        'Film',
        'Autor',
        'Bauwerk',
        'Werkzeug',
        'Kleidung',
        'Farbe',
        'Fach',
        'Möbelstück',
        'Gewächs',
        'Fast food',
        'Synonym für Geld',
        'Fluss',
        'Stadt im Inland',
        'Stadt im Ausland',
        'Land',
        'Name',
        'Weiblicher Name',
        'Männlicher Name',
        'Geschlechtsneutraler Name',
        'Ernährungsform',
        'Haustier',
        'In der Küche',
        'Im Schlafzimmer',
        'Im Wohnzimmer',
        'Bei den Großeltern',
        'Darf auf einer Reise nicht fehlen',
        'In der Handtasche',
        'Im Auto',
        'Im Weltall',
        'Auf dem Festival',
        'Kostüm',
        'So würde dein Museum heißen',
        'Trennungsgrund',
        'Macht attraktiv',
        'In einer Beziehung',
        'Hobby',
        'Essen',
        'Lebensmittel',
        'Im Kühlschrank',
        'Gesellschaftsspiel',
        'Videospiel',
        'Webseite',
        'Filmgenre',
        'Musikgenre',
        'Chemisches Element',
        'IT Begriff',
        'Schiff',
        'Snack',
        'Musikinstrument',
        'Romanfigur',
        'Fest',
        'In einer Freundschaft',
        'Erfindung',
        'Gewürz',
        'Süßigkeit',
        'Spielzeug',
        'Kindheitsheld',
        'Beim Date',
        'Fantasyfigur',
        'Superheld',
        'Hat einen Griff',
        'Kinderlied',
        'Sprichwort',
        'Grund für Schulverweis',
        'Körperteil',
        'Kleiner als ein Tennisball',
        'Besteht aus Metall',
        'Besteht aus Plastik',
        'Größer als ein Auto',
        'Wildes Tier',
        'Sportart',
        'Beruf',
        'Im Haushalt',
        'Verb',
        'Adjektiv',
        'Nomen',
        'In der Schule',
        'Sehenswürdigkeit',
        'Elektrogerät',
        'Im Baumarkt',
        'Stört bei der Arbeit',
        'Arbeitsunfall',
        'Stimmungskiller',
        'Biermarke',
        'Automarke',
        'Beim Raclette',
        'Im Zoo',
        'Sportler',
        'Wassertier',
        'Auf der Postkarte',
        'Eissorte',
        'Sportgerät',
        'Campingausrüstung',
        'Im Labor',
        'Drinnen',
        'Draußen',
        'Pokemon',
        'Figur aus Harry Potter',
        'Figur aus Herr der Ringe',
        'Aus Star Wars',
        'In der Zukunft',
        'Im Badezimmer',
        'Da möchte ich übernachten',
        'Zum Entspannen',
        'Getränk',
        'Ist kreativ',
        'Kann wachsen',
        'Kann schrumpfen',
        'leichter als 1kg',
        'schwerer als 10kg',
        'Gutes Versteck',
        'Gerät',
        'Braucht Strom',
        'Unter Wasser',
        'Aus der Physik',
        'Aus Biologie',
        'Typisch deutsch',
        'Buchtitel',
        'So würde mein Haustier heißen',
        'Im Handy',
        'Kuchen',
        'Pizzabelag',
        'Haushaltsaufgabe',
        'Davon mache ich Fotos',
        'Stört mich',
        'Mag ich',
        'Mein Wunsch Legoset',
        'Beim wandern',
        'App',
        'Reiseziel',
        'Typisch Frau',
        'Typisch Mann',
        'Typisch Büro',
        'Hat mehr als zwei Beine',
        'Hat Flügel',
        'Hat Klauen',
        'Hat Fell',
        'Hat Hufe',
        'Ist niedlich',
        'Ist hässlich',
        'Das wünsche ich mir',
        'Beim Arzt',
        'Tierbaby',
        'Im Schwimmbad',
        'Braucht man zum Putzen',
        'Teesorte',
        'In der Drogerie',
        'In der Welt will ich leben',
        'Im trend',
        'Stylisch',
        'Sternzeichen',
        'Sternbild',
        'Kosename',
        'Youtube Kanal',
        'An Weihnachten',
        'Im Judentum',
        'Im Islam',
        'Im Christentum',
        'Im Buddhismus',
        'In der Bibel',
        'Bei einer Übernachtung',
        'In der Nacht',
        'Im Internet',
        'Auf dem Flohmarkt',
        'Auf der Kirmes',
        'Nehme ich mit auf eine einsame Insel',
        'Braucht man zum Überleben',
        'Kann leuchten',
        'Glitzert',
        'In einer Bäckerei',
        'Auf dem Schminktisch',
        'Am Strand',
        'In der Politik',
        'Hier im Raum',
        'Auf dem Bauernhof',
        'Schauspieler',
        'Vogel',
        'Insekt',
        'Wetterlage',
        'Kinderserie',
        'So würde mein Film heißen',
        'So würde mein Buch heißen',
        'Klamottenmarke',
        'Markenname',
        'Kann man in der Mikrowelle kochen',
        'Rätselart',
        'Kompliment',
        'Das würde ich gerne erfinden',
        'Auf dem Wasser',
        'Die Person links von mir ist...',
        'Die Person rechts von mir ist...',
        'Ich bin...',
      ],
      en: [
        'TV series',
        'Movie',
        'Author',
        'Building',
        'Tool',
        'Item of clothing',
        'Color',
        'School subject',
        'Piece of furniture',
        'Plant',
        'Fast food',
        'Word for money',
        'River',
        'City in your country',
        'City abroad',
        'Country',
        'First name',
        'Female first name',
        'Male first name',
        'Gender-neutral first name',
        'Type of diet',
        'Pet',
        'In the kitchen',
        'In the bedroom',
        'In the living room',
        'At the grandparents house',
        'Must-have for a trip',
        'In a handbag',
        'In a car',
        'In outer space',
        'At a festival',
        'Costume',
        'Name for your museum',
        'Reason for a breakup',
        'Makes someone attractive',
        'In a relationship',
        'Hobby',
        'Meal',
        'Food',
        'In the fridge',
        'Board game',
        'Video game',
        'Website',
        'Movie genre',
        'Music genre',
        'Chemical element',
        'IT term',
        'Ship',
        'Snack',
        'Musical instrument',
        'Novel character',
        'Celebration',
        'In a friendship',
        'Invention',
        'Spice',
        'Candy',
        'Toy',
        'Childhood hero',
        'On a date',
        'Fantasy character',
        'Superhero',
        'Has a handle',
        'Childrens song',
        'Proverb',
        'Reason for school suspension',
        'Body part',
        'Smaller than a tennis ball',
        'Made of metal',
        'Made of plastic',
        'Larger than a car',
        'Wild animal',
        'Sport',
        'Profession',
        'In the household',
        'Verb',
        'Adjective',
        'Noun',
        'At school',
        'Tourist attraction',
        'Electrical appliance',
        'At a hardware store',
        'Annoying at work',
        'Workplace accident',
        'Mood killer',
        'Beer brand',
        'Car brand',
        'At a dinner party',
        'At the zoo',
        'Athlete',
        'Aquatic animal',
        'On a postcard',
        'Ice cream flavor',
        'Sports equipment',
        'Camping gear',
        'In a laboratory',
        'Indoors',
        'Outdoors',
        'Pokémon',
        'Harry Potter character',
        'Lord of the Rings character',
        'From Star Wars',
        'In the future',
        'In the bathroom',
        'Place to spend the night',
        'For relaxing',
        'Drink',
        'Is creative',
        'Can grow',
        'Can shrink',
        'Lighter than one kilogram',
        'Heavier than ten kilograms',
        'Good hiding place',
        'Device',
        'Needs electricity',
        'Underwater',
        'From physics',
        'From biology',
        'Typically British',
        'Book title',
        'Name for my pet',
        'On a phone',
        'Cake',
        'Pizza topping',
        'Household chore',
        'Something I photograph',
        'Annoys me',
        'Something I like',
        'Dream LEGO set',
        'While hiking',
        'App',
        'Travel destination',
        'Typically female',
        'Typically male',
        'Typical office item',
        'Has more than two legs',
        'Has wings',
        'Has claws',
        'Has fur',
        'Has hooves',
        'Is cute',
        'Is ugly',
        'Something I wish for',
        'At the doctors office',
        'Baby animal',
        'At a swimming pool',
        'Needed for cleaning',
        'Tea variety',
        'At a drugstore',
        'A world I would live in',
        'Trendy',
        'Stylish',
        'Zodiac sign',
        'Constellation',
        'Pet name',
        'YouTube channel',
        'At Christmas',
        'In Judaism',
        'In Islam',
        'In Christianity',
        'In Buddhism',
        'In the Bible',
        'At a sleepover',
        'At night',
        'On the internet',
        'At a flea market',
        'At a fairground',
        'Take to a desert island',
        'Needed for survival',
        'Can glow',
        'Sparkles',
        'In a bakery',
        'On a dressing table',
        'At the beach',
        'In politics',
        'In this room',
        'On a farm',
        'Actor',
        'Bird',
        'Insect',
        'Weather condition',
        'Childrens series',
        'Title of my movie',
        'Title of my book',
        'Clothing brand',
        'Brand name',
        'Microwaveable food',
        'Type of puzzle',
        'Compliment',
        'Something I would invent',
        'On the water',
        'The person to my left is …',
        'The person to my right is …',
        'I am …',
      ],
    },
  },
  {
    id: 'movies-tv',
    title: {
      de: 'Filme & Serien',
      en: 'Movies & TV',
    },
    questions: {
      de: [
        'Aus "Harry Potter"',
        'Aus "Herr der Ringe"',
        'Aus "Star Wars"',
        'Aus "Game of Thrones"',
        'Aus "Breaking Bad"',
        'Aus "The Walking Dead"',
        'Aus "The Big Bang Theory"',
        'Aus "The Simpsons"',
        'Aus "South Park"',
        'Aus "Spongebob"',
        'Aus "Family Guy"',
        'Aus "How I met your mother"',
        'Aus "Scrubs"',
        'Aus "Star Trek"',
        'Aus "The Office"',
        'Aus "Dune"',
        'Aus "The Witcher"',
        'Aus "The Mandalorian"',
        'Aus "The Boys"',
        'Aus dem Marvel Cinematic Universe',
        'Aus dem DC Extended Universe',
        'Aus "Arrow"',
        'Aus "Dr. Who"',
        'Aus "Wednesday"',
        'Aus "The Expanse"',
        'Aus "The Orville"',
        'Aus "The Umbrella Academy"',
        'Aus "Dexter"',
        'Aus "Supernatural"',
        'Aus "Stranger Things"',
        'Aus "Dr. House"',
        'Aus "The Mentalist"',
        'Aus "Pokémon"',
        'Liebesfilm',
        'Actionfilm',
        'Horrorfilm',
        'Science-Fiction-Film',
        'Fantasyfilm',
        'Animationsfilm',
        'Dokumentarfilm',
        'Kriegsfilm',
        'Western',
        'Historienfilm',
        'Katastrophenfilm',
        'Märchenfilm',
        'Filmreihe',
        'Film mit Will Smith',
        'Film mit Tom Hanks',
        'Film mit Leonardo DiCaprio',
        'Film mit Johnny Depp',
        'Film mit Brad Pitt',
        'Film mit Robert Downey Jr.',
        'Film mit Dwayne Johnson',
        'Film mit Vin Diesel',
        'Film mit Arnold Schwarzenegger',
        'Film mit Sylvester Stallone',
        'Film mit Harrison Ford',
        'Film mit Bruce Willis',
        'Film mit Keanu Reeves',
        'Film mit Jackie Chan',
        'Film mit einer Zeitreise',
        'Serie mit einer Zeitreise',
        'Film, der im Weltall spielt',
        'Serie, die im Weltall spielt',
        'Film mit einem Roboter',
        'Film mit einem Drachen',
        'Film mit einem sprechenden Tier',
        'Film über eine Reise',
        'Film, der auf einem Buch basiert',
        'Serie, die auf einem Buch basiert',
        'Film mit einem unerwarteten Ende',
        'Film mit einer Verfolgungsjagd',
        'Film über einen Raubüberfall',
        'Film über Musik',
        'Film über Sport',
        'Film, der auf einer Insel spielt',
        'Film mit einem Monster',
        'Film mit einem Vampir',
        'Film mit einem Zombie',
        'Film mit einem Geist',
        'Film, der im Winter spielt',
        'Weihnachtsfilm',
        'Roadmovie',
        'Musicalfilm',
        'Thriller',
        'Kriminalfilm',
        'Spionagefilm',
        'Sportserie',
        'Krankenhausserie',
        'Krimiserie',
        'Sitcom',
        'Zeichentrickserie',
        'Anime-Serie',
        'Miniserie',
        'Serie mit einer erfundenen Stadt',
        'Serie über eine Familie',
        'Serie, die in einer Schule spielt',
        'Serie mit einem Detektiv',
        'Serie mit übernatürlichen Kräften',
        'Film mit einer weiblichen Hauptfigur',
        'Figur aus einem Pixar-Film',
        'Figur aus einem Disney-Film',
        'Figur aus einem Studio-Ghibli-Film',
        'Aus Avatar: Der Herr der Elemente',
        'Aus Friends',
        'Aus Brooklyn Nine-Nine',
        'Aus Sherlock',
        'Aus Buffy – Im Bann der Dämonen',
        'Aus Gilmore Girls',
        'Aus Lost',
        'Aus Futurama',
        'Aus Adventure Time',
        'Aus Arcane',
        'Aus Dragon Ball',
        'Aus One Piece',
        'Film mit Meryl Streep',
        'Film mit Viola Davis',
        'Film mit Kate Winslet',
        'Film mit Natalie Portman',
        'Film mit Michelle Yeoh',
      ],
      en: [
        'From Harry Potter',
        'From The Lord of the Rings',
        'From Star Wars',
        'From Game of Thrones',
        'From Breaking Bad',
        'From The Walking Dead',
        'From The Big Bang Theory',
        'From The Simpsons',
        'From South Park',
        'From SpongeBob SquarePants',
        'From Family Guy',
        'From How I Met Your Mother',
        'From Scrubs',
        'From Star Trek',
        'From The Office',
        'From Dune',
        'From The Witcher',
        'From The Mandalorian',
        'From The Boys',
        'From the Marvel Cinematic Universe',
        'From the DC universe',
        'From Arrow',
        'From Doctor Who',
        'From Wednesday',
        'From The Expanse',
        'From The Orville',
        'From The Umbrella Academy',
        'From Dexter',
        'From Supernatural',
        'From Stranger Things',
        'From House M.D.',
        'From The Mentalist',
        'From Pokémon',
        'Romance movie',
        'Action movie',
        'Horror movie',
        'Science-fiction movie',
        'Fantasy movie',
        'Animated movie',
        'Documentary',
        'War movie',
        'Western',
        'Historical movie',
        'Disaster movie',
        'Fairy-tale movie',
        'Movie franchise',
        'Movie starring Will Smith',
        'Movie starring Tom Hanks',
        'Movie starring Leonardo DiCaprio',
        'Movie starring Johnny Depp',
        'Movie starring Brad Pitt',
        'Movie starring Robert Downey Jr.',
        'Movie starring Dwayne Johnson',
        'Movie starring Vin Diesel',
        'Movie starring Arnold Schwarzenegger',
        'Movie starring Sylvester Stallone',
        'Movie starring Harrison Ford',
        'Movie starring Bruce Willis',
        'Movie starring Keanu Reeves',
        'Movie starring Jackie Chan',
        'Movie involving time travel',
        'TV series involving time travel',
        'Movie set in space',
        'TV series set in space',
        'Movie featuring a robot',
        'Movie featuring a dragon',
        'Movie featuring a talking animal',
        'Movie about a journey',
        'Movie based on a book',
        'TV series based on a book',
        'Movie with an unexpected ending',
        'Movie with a chase scene',
        'Heist movie',
        'Movie about music',
        'Movie about sports',
        'Movie set on an island',
        'Movie featuring a monster',
        'Movie featuring a vampire',
        'Movie featuring a zombie',
        'Movie featuring a ghost',
        'Movie set in winter',
        'Christmas movie',
        'Road movie',
        'Movie musical',
        'Thriller',
        'Crime movie',
        'Spy movie',
        'Sports series',
        'Medical drama series',
        'Crime series',
        'Sitcom',
        'Animated TV series',
        'Anime series',
        'Miniseries',
        'TV series with a fictional town',
        'TV series about a family',
        'TV series set in a school',
        'TV series featuring a detective',
        'TV series featuring supernatural powers',
        'Movie with a female protagonist',
        'Character from a Pixar movie',
        'Character from a Disney movie',
        'Character from a Studio Ghibli movie',
        'From Avatar: The Last Airbender',
        'From Friends',
        'From Brooklyn Nine-Nine',
        'From Sherlock',
        'From Buffy the Vampire Slayer',
        'From Gilmore Girls',
        'From Lost',
        'From Futurama',
        'From Adventure Time',
        'From Arcane',
        'From Dragon Ball',
        'From One Piece',
        'Movie starring Meryl Streep',
        'Movie starring Viola Davis',
        'Movie starring Kate Winslet',
        'Movie starring Natalie Portman',
        'Movie starring Michelle Yeoh',
      ],
    },
  },
  {
    id: 'everyday-chaos',
    title: {de: 'Alltag & Chaos', en: 'Everyday & Chaos'},
    questions: {
      de: [
        'Grund fürs Zuspätkommen',
        'Liegt immer im Weg',
        'Geht montags kaputt',
        'Vergisst man beim Einkaufen',
        'Peinlicher Autokorrekturfehler',
        'Ausrede im Homeoffice',
        'Macht der Nachbar zu laut',
        'Verschwindet im Haushalt',
        'Findet man unter dem Sofa',
        'Schlechter Ort für einen Schlüssel',
        'Grund für Chaos in der Küche',
        'Unnötiger Onlinekauf',
        'Wird ständig verlegt',
        'Typischer WG-Streit',
        'Macht einen Morgen schlimmer',
        'Seltsamer Paketinhalt',
        'Steht seit Monaten auf der To-do-Liste',
        'Wird im Kühlschrank vergessen',
        'Unpassender Klingelton',
        'Dumme Verletzung',
        'Seltsamer Fund in der Jackentasche',
        'Grund für einen Stromausfall',
        'Spontane Wochenendidee',
        'Verdächtiges Geräusch nachts',
        'Muss dringend repariert werden',
        'Schlechtes Passwort',
        'Komischer WLAN-Name',
        'Grund, das Haus nicht zu verlassen',
        'Kleine Alltagskatastrophe',
        'Unnützes Küchengerät',
        'Verboten im Treppenhaus',
        'Tut man statt aufzuräumen',
        'Seltsame Erinnerung im Kalender',
        'Macht man nur aus Höflichkeit',
        'Darf niemand im Browserverlauf sehen',
        'Schlechte Idee vor dem Schlafengehen',
        'Grund für eine Beschwerde',
        'Merkwürdige Fundsache',
        'Wird viel zu lange aufgehoben',
        'Sollte man nicht in die Mikrowelle legen',
      ],
      en: [
        'Reason for being late',
        'Always in the way',
        'Breaks on a Monday',
        'Forgotten at the grocery store',
        'Embarrassing autocorrect fail',
        'Work-from-home excuse',
        'The neighbor does it too loudly',
        'Keeps disappearing at home',
        'Found under the sofa',
        'Bad place for a key',
        'Cause of chaos in the kitchen',
        'Unnecessary online purchase',
        'Constantly misplaced',
        'Typical roommate argument',
        'Makes a morning worse',
        'Strange parcel content',
        'On the to-do list for months',
        'Forgotten in the fridge',
        'Inappropriate ringtone',
        'Ridiculous injury',
        'Odd thing in a jacket pocket',
        'Cause of a power outage',
        'Spontaneous weekend idea',
        'Suspicious noise at night',
        'Needs urgent repair',
        'Bad password',
        'Weird Wi-Fi name',
        'Reason not to leave the house',
        'Tiny everyday disaster',
        'Useless kitchen gadget',
        'Banned in the stairwell',
        'Done instead of tidying up',
        'Strange calendar reminder',
        'Done only to be polite',
        'Should not appear in browser history',
        'Bad idea before bedtime',
        'Reason to complain',
        'Odd lost property',
        'Kept for far too long',
        'Should not go in a microwave',
      ],
    },
  },
  {
    id: 'fantasy-rpg',
    title: {de: 'Fantasy & Rollenspiel', en: 'Fantasy & Role-playing'},
    questions: {
      de: [
        'Fantasywesen',
        'Magischer Gegenstand',
        'Name einer Taverne',
        'Zauberspruch',
        'Drachenname',
        'Grund für eine Quest',
        'Fundstück im Dungeon',
        'Charakterklasse',
        'Fantasyberuf',
        'Name eines Königreichs',
        'Fluch',
        'Segen einer Gottheit',
        'Monsterfähigkeit',
        'Zutat für einen Trank',
        'Falle im Dungeon',
        'Gerücht in der Taverne',
        'Name einer Abenteurergruppe',
        'Makel eines Helden',
        'Schatz eines Drachen',
        'Verbotene Magieschule',
        'Gottheit',
        'Untotenart',
        'Grund für einen Pakt',
        'Fähigkeit eines Artefakts',
        'Begegnung im Wald',
        'Peinlicher Barden-Song',
        'Problem eines Paladins',
        'Ausrede eines Schurken',
        'Eigenart eines Zauberers',
        'Name eines Dungeons',
        'Währung einer Fantasywelt',
        'Transportmittel in einer Fantasywelt',
        'Begleiter eines Helden',
        'Etwas in der Tasche eines Goblins',
        'Titel eines finsteren Herrschers',
        'Prophezeiung',
        'Grund für einen kritischen Fehlschlag',
        'Mimic-Versteck',
        'Belohnung für eine Nebenquest',
        'Regel in einer Magierakademie',
      ],
      en: [
        'Fantasy creature',
        'Magic item',
        'Tavern name',
        'Spell',
        'Dragon name',
        'Reason for a quest',
        'Found in a dungeon',
        'Character class',
        'Fantasy profession',
        'Kingdom name',
        'Curse',
        'Blessing from a deity',
        'Monster ability',
        'Potion ingredient',
        'Dungeon trap',
        'Tavern rumor',
        'Adventuring party name',
        'Heroic flaw',
        'Part of a dragon’s hoard',
        'Forbidden school of magic',
        'Deity',
        'Type of undead',
        'Reason for a pact',
        'Artifact ability',
        'Forest encounter',
        'Embarrassing bard song',
        'Paladin problem',
        'Rogue’s excuse',
        'Wizard’s odd habit',
        'Dungeon name',
        'Fantasy currency',
        'Fantasy mode of transport',
        'Hero’s companion',
        'In a goblin’s pocket',
        'Title of a dark ruler',
        'Prophecy',
        'Reason for a critical failure',
        'Mimic hiding place',
        'Side-quest reward',
        'Rule at a magic academy',
      ],
    },
  },
  {
    id: 'gaming-nerd',
    title: {de: 'Gaming & Nerdkultur', en: 'Gaming & Nerd Culture'},
    questions: {
      de: [
        'Videospielcharakter',
        'Spielekonsole',
        'Bossgegner',
        'Indie-Spiel',
        'Gaming-Genre',
        'Grund für einen Ragequit',
        'Item in einer Lootbox',
        'Name eines Clans',
        'NPC-Spruch',
        'Schlechtes Achievement',
        'Übermächtige Fähigkeit',
        'Speedrun-Trick',
        'Retro-Spiel',
        'Brettspielmechanik',
        'Science-Fiction-Technologie',
        'Robotername',
        'Superkraft mit Nachteil',
        'Programmiersprache',
        'Linux-Distribution',
        'IT-Abkürzung',
        'Fehlermeldung',
        'Grund für Serverausfall',
        'Teil eines Gaming-PCs',
        'Tabletop-Miniatur',
        'Sammelkartenspiel',
        'Name eines Raumschiffs',
        'Alien-Spezies',
        'Zeitreise-Paradoxon',
        'Convention-Kostüm',
        'Fan-Theorie',
        'Völlig unnötiges Gadget',
        'KI mit schlechtem Namen',
        'Hacker-Alias',
        'Name eines Endgegners',
        'Cheatcode',
        'Ding auf dem Schreibtisch',
      ],
      en: [
        'Video game character',
        'Game console',
        'Boss enemy',
        'Indie game',
        'Game genre',
        'Reason for a rage quit',
        'Loot-box item',
        'Clan name',
        'NPC catchphrase',
        'Bad achievement',
        'Overpowered ability',
        'Speedrun trick',
        'Retro game',
        'Board-game mechanic',
        'Science-fiction technology',
        'Robot name',
        'Superpower with a downside',
        'Programming language',
        'Linux distribution',
        'IT abbreviation',
        'Error message',
        'Reason for a server outage',
        'Part of a gaming PC',
        'Tabletop miniature',
        'Trading card game',
        'Spaceship name',
        'Alien species',
        'Time-travel paradox',
        'Convention costume',
        'Fan theory',
        'Completely unnecessary gadget',
        'Badly named AI',
        'Hacker alias',
        'Final boss name',
        'Cheat code',
        'On the desk',
      ],
    },
  },
  {
    id: 'party-dark-humor',
    title: {de: 'Party & schwarzer Humor', en: 'Party & Dark Humor'},
    questions: {
      de: [
        'Schlechter Grund anzustoßen',
        'Peinlicher Party-Moment',
        'Kater-Ausrede',
        'Warnschild auf einer WG-Party',
        'Grund für Hausverbot',
        'Seltsamer Cocktailname',
        'Was man beim ersten Date verschweigt',
        'Unpassendes Hochzeitsgeschenk',
        'Letzte Worte vor einer schlechten Idee',
        'Grund für einen Notruf',
        'Tattoo, das man bereut',
        'Schlechter Name für ein Bestattungsunternehmen',
        'Unangebrachtes Beerdigungslied',
        'Miese Grabinschrift',
        'Verdächtiges Alibi',
        'Grund, aus einer Bar zu fliegen',
        'Etwas im Flachmann',
        'Partyspiel mit Verletzungsgefahr',
        'Schlimmer Mitternachtssnack',
        'Grund für eine Familienfehde',
        'Darf nicht in die Gruppenchat-Historie',
        'Unpassender Trinkspruch',
        'Schrecklicher Junggesellenabschied',
        'Grund für eine spontane Flucht',
        'Was nach „Halt mal mein Bier“ passiert',
        'Kreative Beleidigung',
        'Ding, das auf einer Party brennt',
        'Schlechter Ort zum Aufwachen',
        'Grund für eine toxische Bewertung',
        'Party-Motto mit Warnsignal',
        'Wird am nächsten Morgen geleugnet',
        'Schlechtes Geschenk vom Ex',
        'Dumme Mutprobe',
        'Grund für eine sehr kurze Karriere',
        'Unnötig dramatischer Abgang',
        'Name einer Metalband',
        'Morbider Kosename',
        'Ausrede gegenüber der Polizei',
        'Etwas, das Oma nicht hören sollte',
        'Grund, sofort nüchtern zu werden',
      ],
      en: [
        'Bad reason for a toast',
        'Embarrassing party moment',
        'Hangover excuse',
        'Warning sign at a house party',
        'Reason for a venue ban',
        'Weird cocktail name',
        'Hidden on a first date',
        'Inappropriate wedding present',
        'Last words before a bad idea',
        'Reason for an emergency call',
        'Regrettable tattoo',
        'Bad name for a funeral home',
        'Inappropriate funeral song',
        'Terrible epitaph',
        'Suspicious alibi',
        'Reason for being thrown out of a bar',
        'Inside a hip flask',
        'Party game with injury risk',
        'Awful midnight snack',
        'Reason for a family feud',
        'Must not remain in the group-chat history',
        'Inappropriate toast',
        'Disastrous bachelor party',
        'Reason for a sudden escape',
        'What follows “hold my beer”',
        'Creative insult',
        'On fire at a party',
        'Bad place to wake up',
        'Reason for a one-star review',
        'Party theme with red flags',
        'Denied the next morning',
        'Bad present from an ex',
        'Stupid dare',
        'Reason for a very short career',
        'Needlessly dramatic exit',
        'Metal band name',
        'Morbid pet name',
        'Excuse given to the police',
        'Grandma should not hear this',
        'Reason to become sober instantly',
      ],
    },
  },
  {
    id: 'nature-animals',
    title: {de: 'Natur & Tiere', en: 'Nature & Animals'},
    questions: {
      de: [
        'Säugetier',
        'Vogelart',
        'Reptil',
        'Amphibie',
        'Insekt',
        'Meerestier',
        'Nachtaktives Tier',
        'Giftiges Tier',
        'Ausgestorbenes Tier',
        'Tier mit Tarnung',
        'Zugvogel',
        'Bestäuber',
        'Tierischer Rekordhalter',
        'Lebensraum',
        'Baumart',
        'Heilpflanze',
        'Giftpflanze',
        'Pilzart',
        'Gestein',
        'Mineral',
        'Wetterphänomen',
        'Naturkatastrophe',
        'Ökosystem',
        'Nationalpark',
        'Gebirgszug',
        'Flusslandschaft',
        'Spur eines Tieres',
        'Tierlaut',
        'Überlebensstrategie',
        'Symbiose',
        'Invasive Art',
        'Bedrohte Art',
        'Fossil',
        'Dinosaurier',
        'Pflanze für den Garten',
        'Etwas im Kompost',
        'Fundstück am Strand',
        'Tier mit ungewöhnlichem Namen',
        'Naturphänomen am Nachthimmel',
      ],
      en: [
        'Mammal',
        'Bird species',
        'Reptile',
        'Amphibian',
        'Insect',
        'Marine animal',
        'Nocturnal animal',
        'Venomous animal',
        'Extinct animal',
        'Animal with camouflage',
        'Migratory bird',
        'Pollinator',
        'Animal record holder',
        'Habitat',
        'Tree species',
        'Medicinal plant',
        'Poisonous plant',
        'Fungus',
        'Rock',
        'Mineral',
        'Weather phenomenon',
        'Natural disaster',
        'Ecosystem',
        'National park',
        'Mountain range',
        'River landscape',
        'Animal track',
        'Animal sound',
        'Survival strategy',
        'Symbiosis',
        'Invasive species',
        'Endangered species',
        'Fossil',
        'Dinosaur',
        'Garden plant',
        'In a compost heap',
        'Found on a beach',
        'Animal with an unusual name',
        'Natural phenomenon in the night sky',
      ],
    },
  },
  {
    id: 'knowledge-science',
    title: {de: 'Wissen & Wissenschaft', en: 'Knowledge & Science'},
    questions: {
      de: [
        'Physikalische Einheit',
        'Chemisches Element',
        'Teil eines Atoms',
        'Laborgerät',
        'Naturgesetz',
        'Teilchen',
        'Säure',
        'Base',
        'Metall',
        'Edelgas',
        'Organ des Menschen',
        'Knochen',
        'Hormon',
        'Krankheitserreger',
        'Erbmerkmal',
        'Wissenschaftliche Theorie',
        'Mathematischer Begriff',
        'Geometrische Form',
        'Primzahl',
        'Astronomisches Objekt',
        'Sternbild',
        'Raumfahrtmission',
        'Entdecker oder Erfinder',
        'Wissenschaftlerin',
        'Messinstrument',
        'Energiequelle',
        'Materialeigenschaft',
        'Aggregatzustand',
        'Optisches Phänomen',
        'Evolutionäre Anpassung',
        'Geologische Epoche',
        'Archäologischer Fund',
        'Philosophischer Begriff',
        'Psychologischer Effekt',
        'Wirtschaftlicher Fachbegriff',
        'Sprache mit besonderer Schrift',
        'Nobelpreis-Kategorie',
        'Experiment für die Schule',
      ],
      en: [
        'Physical unit',
        'Chemical element',
        'Part of an atom',
        'Laboratory equipment',
        'Law of physics',
        'Particle',
        'Acid',
        'Base',
        'Metal',
        'Noble gas',
        'Human organ',
        'Bone',
        'Hormone',
        'Pathogen',
        'Inherited trait',
        'Scientific theory',
        'Mathematical term',
        'Geometric shape',
        'Prime number',
        'Astronomical object',
        'Constellation',
        'Space mission',
        'Explorer or inventor',
        'Female scientist',
        'Measuring instrument',
        'Energy source',
        'Material property',
        'State of matter',
        'Optical phenomenon',
        'Evolutionary adaptation',
        'Geological period',
        'Archaeological discovery',
        'Philosophical term',
        'Psychological effect',
        'Economic term',
        'Language with a distinctive script',
        'Nobel Prize category',
        'School science experiment',
      ],
    },
  },
  {
    id: 'food-drinks',
    title: {de: 'Essen & Getränke', en: 'Food & Drinks'},
    questions: {
      de: [
        'Gemüsesorte',
        'Obstsorte',
        'Hülsenfrucht',
        'Käsesorte',
        'Brotsorte',
        'Nudelgericht',
        'Reisgericht',
        'Suppe',
        'Salat',
        'Dessert',
        'Kuchen',
        'Gebäck',
        'Gewürz',
        'Kräuter',
        'Soße',
        'Dip',
        'Streetfood',
        'Vegetarisches Gericht',
        'Vegane Zutat',
        'Fermentiertes Lebensmittel',
        'Frühstück',
        'Mitternachtssnack',
        'Picknick-Essen',
        'Party-Snack',
        'Eissorte',
        'Pizzabelag',
        'Zutat im Curry',
        'Etwas vom Grill',
        'Heißgetränk',
        'Erfrischungsgetränk',
        'Cocktail',
        'Mocktail',
        'Biersorte',
        'Weinregion',
        'Seltsame Geschmackskombination',
        'Gericht mit lustigem Namen',
        'Essen aus einer Fantasywelt',
        'Kulinarisches Souvenir',
        'Etwas Knuspriges',
        'Etwas, das niemals auf Pizza gehört',
      ],
      en: [
        'Vegetable',
        'Fruit',
        'Legume',
        'Cheese',
        'Type of bread',
        'Pasta dish',
        'Rice dish',
        'Soup',
        'Salad',
        'Dessert',
        'Cake',
        'Pastry',
        'Spice',
        'Herb',
        'Sauce',
        'Dip',
        'Street food',
        'Vegetarian dish',
        'Vegan ingredient',
        'Fermented food',
        'Breakfast food',
        'Midnight snack',
        'Picnic food',
        'Party snack',
        'Ice cream flavor',
        'Pizza topping',
        'Curry ingredient',
        'Something from a barbecue',
        'Hot drink',
        'Soft drink',
        'Cocktail',
        'Mocktail',
        'Type of beer',
        'Wine region',
        'Odd flavor combination',
        'Dish with a funny name',
        'Food from a fantasy world',
        'Culinary souvenir',
        'Something crunchy',
        'Something that never belongs on pizza',
      ],
    },
  },
  {
    id: 'travel-places',
    title: {de: 'Reisen & Orte', en: 'Travel & Places'},
    questions: {
      de: [
        'Hauptstadt',
        'Insel',
        'Gebirge',
        'Ort am Meer',
        'Stadt für ein Wochenende',
        'Reiseziel im Winter',
        'Reiseziel im Sommer',
        'Ort für Sternenbeobachtung',
        'Sehenswürdigkeit',
        'Museum',
        'Burg oder Schloss',
        'Verkehrsmittel',
        'Ding im Handgepäck',
        'Wird am Bahnhof ausgerufen',
        'Flughafenproblem',
        'Typisches Souvenir',
        'Kulinarisches Reiseziel',
        'Ort mit Vulkanen',
        'Ort im Regenwald',
        'Ort in der Wüste',
        'Ort am Polarkreis',
        'Historische Stadt',
        'Fiktiver Urlaubsort',
        'Roadtrip-Stopp',
        'Ungewöhnliche Unterkunft',
        'Grund für eine Grenzkontrolle',
        'Satz aus einem Sprachführer',
        'Reisepanne',
        'Urlaubsaktivität',
        'Wanderziel',
        'Ort für eine Zeitreise',
        'Stadt mit berühmter Architektur',
        'Land mit mehreren Amtssprachen',
        'Ort mit besonderem Nachtleben',
        'Reiseziel ohne Auto',
        'Ort für eine Expedition',
      ],
      en: [
        'Capital city',
        'Island',
        'Mountain range',
        'Place by the sea',
        'City for a weekend',
        'Winter destination',
        'Summer destination',
        'Place for stargazing',
        'Tourist attraction',
        'Museum',
        'Castle or palace',
        'Mode of transport',
        'In carry-on luggage',
        'Announced at a train station',
        'Airport problem',
        'Typical souvenir',
        'Culinary destination',
        'Place with volcanoes',
        'Place in a rainforest',
        'Place in a desert',
        'Place near the Arctic Circle',
        'Historic city',
        'Fictional holiday destination',
        'Road-trip stop',
        'Unusual accommodation',
        'Reason for a border check',
        'Phrasebook sentence',
        'Travel mishap',
        'Holiday activity',
        'Hiking destination',
        'Place for time travel',
        'City with famous architecture',
        'Country with several official languages',
        'Place with special nightlife',
        'Car-free destination',
        'Place for an expedition',
      ],
    },
  },
];

export const getBuiltInQuestionPacks = (language: Language): QuestionPack[] =>
  localizedPacks.map(pack => ({
    id: pack.id,
    title: pack.title[language],
    questions: [...pack.questions[language]],
  }));

export const builtInPackIds = localizedPacks.map(pack => pack.id);
