// list of questions for the quiz. Dictionary with multiple sets of questions

export const questionSet = [
    {
        title: 'Standard',
        questions: [ 
        'Physiker*in',
        'Stadt in Deutschland',
        'Macht Spaß',
        'Maler*in',
        'Europäisches Land',
        'Lieblingssport',
        'Schauspieler*in',
        'Tier mit vier Beinen',
        'Buchtitel',
        'Dessert',
        'Fußballverein',
        'Musikinstrument',
        'Hauptstadt eines Landes',
        'Wissenschaftler*in',
        'Schauspielerin*in',
        'Politiker*in',
        'Hobby',
        'Gemälde',
        'Modelabel',
        'Entdecker*in',
        'Schriftsteller*in',
        'Monument',
        'Sänger*in',
        'Filmfigur',
        'Lieblingsfilmgenre',
        'Bauwerk',
        'Fernsehserie',
        'Zitat',
        'Persönlichkeit aus der Geschichte',
        'Lieblingsmusikgenre',
        'Modedesigner*in',
        'Roman',
        'Lieblingsurlaubsziel',
        'Sportveranstaltung',
        'Theaterstück',
        'Computerspiel',
        'Naturwissenschaft',
        'Sportteam',
        'Redewendung',
        'Fantasybuch',
        'Science-Fiction-Buch',
        'Kinderbuch',
        'Krimi',
        'Thriller',
        'Lieblingsessen',
        'Lieblingsgetränk',
        'Lieblingsfarbe',
        'Liedtitel',
        'Musikgruppe',
        'Fluss',
        'Land',
        'Stadt',
        'Beruf',
        'Tier',
        'Pflanze',
        'Körperteil',
        'Grund zum Feiern',
        'Schulfach',
        'Hauptstadt',
        'Darf im Urlaub nicht fehlen',
    ],
    },
    {
        title: 'Oh no',
        questions: ['Kein Auto', 'Kein Haus', 'Kein Baum', 'Kein Hund'],

    },
]