// list of questions for the quiz. Dictionary with multiple sets of questions

export const questionSet = [
    {
        title: 'Standard',
        questions: [
            'Serie',
            'Film',
            'Autor',
            'Bauwerk',
            'Werkzeug',
            'Kleidung',
            'Farbe ',
            'Fach ',
            'Möbelstück',
            'Gewächs',
            'Fast food',
            'Synonym für geld ',
            'Fluss',
            'Stadt im Inland ',
            'Stadt im Ausland ',
            'Land',
            'Name',
            'Weiblicher Name ',
            'Männlicher Name ',
            'Ernährungsform',
            'Haustier',
            'In der Küche',
            'Im Schlafzimmer',
            'Im Wohnzimmer',
            'Bei den Großeltern ',
            'Darf auf einer Reise nicht fehlen',
            'In der Handtasche',
            'Im Auto',
            'Im Weltall',
            'Auf dem Festival',
            'Kostüm ',
            'So würde dein Museum heißen',
            'Trennungsgrund',
            'Macht attraktiv ',
            'In einer Beziehung ',
            'Hobby',
            'Essen',
            'Lebensmittel',
            'Im Kühlschrank ',
            'Gesellschaftsspiel',
            'Videospiel ',
            'Webseite',
            'Filmgenre',
            'Musikgenre',
            'Chemisches Element ',
            'IT Begriff ',
            'Schiff',
            'Snack',
            'Musikinstrument',
            'Romanfigur ',
            'Fest',
            'In einer Freundschaft ',
            'Erfindung ',
            'Gewürz ',
            'Süßigkeit ',
            'Spielzeug ',
            'Kindheitsheld',
            'Beim Date ',
            'Fantasyfigur',
            'Superheld',
            'Hat einen Griff',
            'Kinderlied',
            'Sprichwort ',
            'Grund für Schulverweis',
            'Körperteil',
            'Kleiner als ein Tennisball',
            'Besteht aus Metall',
            'Besteht aus Plastik ',
            'Größer als ein Auto',
            'Wildes Tier',
            'Sportart ',
            'Beruf',
            'Im Haushalt ',
            'Verb',
            'Adjektiv',
            'Nomen',
            'In der Schule',
            'Sehenswürdigkeit',
            'Elektrogerät',
            'Im Baumarkt',
            'Stört bei der Arbeit',
            'Arbeitsunfall',
            'Stimmungskiller',
            'Biermarke',
            'Automarke',
            'Beim Raclette',
            'Im Zoo ',
            'Sportler',
            'Wassertier',
            'Auf der Postkarte',
            'Eissorte',
            'Farbe',
            'Sportgerät',
            'Campingausrüstung',
            'Im Labor',
            'Drinnen',
            'Draußen ',
            'Pokemon',
            'Figur aus Harry Potter ',
            'Figur aus Herr der Ringe',
            'Aus Star Wars',
            'In der Zukunft',
            'Im Badezimmer',
            'Da möchte ich übernachten ',
            'Zum Entspannen',
            'Getränk ',
            'Ist kreativ',
            'Kann wachsen',
            'Kann schrumpfen',
            'leichter als 1kg',
            'schwerer als 10kg',
            'Gutes Versteck ',
            'Gerät ',
            'Braucht Strom ',
            'Unter Wasser',
            'Aus der Physik',
            'Aus Biologie',
            'Typisch deutsch ',
            'Buchtitel',
            'So würde mein Haustier heißen',
            'Im Handy',
            'Kuchen',
            'Pizzabelag',
            'Haushaltsaufgabe',
            'Davon mache ich Fotos ',
            'Stört mich',
            'Mag ich',
            'Mein Wunsch Legoset',
            'Beim wandern',
            'App',
            'Reiseziel',
            'Synonym für Frau',
            'Synonym für Mann',
            'Typisch Frau',
            'Typisch Mann',
            'Nerdig ',
            'Typisch Büro',
            'Hat mehr als zwei Beine',
            'Hat Flügel',
            'Hat Klauen',
            'Hat Fell',
            'Hat Hufe',
            'Ist niedlich ',
            'Ist hässlich ',
            'Das wünsche ich mir ',
            'Beim Arzt ',
            'Tierbaby',
            'Im Schwimmbad ',
            'Braucht man zum Putzen',
            'Teesorte',
            'In der Drogerie ',
            'In der Welt will ich leben',
            'Im trend',
            'Stylisch ',
            'Sternzeichen ',
            'Sternbild ',
            'Kosename',
            'Youtube Kanal ',
            'Auf einer Hochzeit ',
            'An Weihnachten ',
            'Im Judentum',
            'Im Islam',
            'Im Christentum ',
            'Im Buddhismus ',
            'In der Bibel',
            'Bei einer Übernachtung ',
            'In der Nacht',
            'Im Internet ',
            'Auf dem Flohmarkt',
            'Auf der Kirmes ',
            'Nehme ich mit auf eine einsame Insel',
            'Braucht man zum Überleben ',
            'Kann leuchten ',
            'Glitzert ',
            'In einer Bäckerei ',
            'Auf dem Schminktisch',
            'Am Strand ',
            'In der Politik ',
            'Hier im Raum',
            'Auf dem Bauernhof',
            'Schauspieler',
            'Vogel',
            'Insekt',
            'Wetterlage',
            'Kinderserie',
            'So würde mein Film heißen',
            'So würde mein Buch heißen',
            'Klamottenmarke',
            'Markenname',
            'Kann man in der Mikrowelle kochen',
            'Rätselart',
            'Kompliment',
            'Das würde ich gerne erfinden',
            'Auf dem Wasser',
        ],
    },
    {
        title: 'Filme und Serien',
        questions: [
            'Aus "Harry Potter"',
            'Aus "Herr der Ringe"',
            'Aus "Star Wars"',
            'Aus "Game of Thrones"',
            'Aus "Breaking Bad"',
            'Aus "The Walking Dead"',
            'Aus "The Big Bang Theory"',
            'Aus "The Simpsons"',
            'Aus "South Park"',
            'Aus "Spongebob"',
            'Aus "Family Guy"',
            'Aus "How I met your mother"',
            'Aus "Scrubs"',
            'Aus "Star Trek"',
            'Aus "The Office"',
            'Aus "Dune"',
            'Aus "The Witcher"',
            'Aus "The Mandalorian"',
            'Aus "The Boys"',
            'Aus dem Marvel Cinematic Universe',
            'Aus dem DC Extended Universe',
            'Aus "Arrow"',
            'Aus "Dr. Who"',
            'Aus "Wednesday"',
            'Aus "The Expanse"',
            'Aus "The Orville"',
            'Aus "The Umbrella Academy"',
            'Aus "Dexter"',
            'Aus "Supernatural"',
            'Aus "Stranger Things"',
            'Aus "Dr. House"',
            'Aus "The Mentalist"',
            'Aus "Pokémon"',
            'Liebesfilm',
            'Actionfilm',
            'Horrorfilm',
            'Science-Fiction-Film',
            'Fantasyfilm',
            'Animationsfilm',
            'Dokumentarfilm',
            'Kriegsfilm',
            'Western',
            'Historienfilm',
            'Katastrophenfilm',
            'Märchenfilm',
            'Filmreihe',
            'Film mit Will Smith',
            'Film mit Tom Hanks',
            'Film mit Leonardo DiCaprio',
            'Film mit Johnny Depp',
            'Film mit Brad Pitt',
            'Film mit Robert Downey Jr.',
            'Film mit Dwayne Johnson',
            'Film mit Vin Diesel',
            'Film mit Arnold Schwarzenegger',
            'Film mit Sylvester Stallone',
            'Film mit Harrison Ford',
            'Film mit Bruce Willis',
            'Film mit Keanu Reeves',
            'Film mit Jackie Chan',
        ]
    },

]