import type {Language} from '../i18n/LocalizationContext';

export type QuestionPack = {
  id: string;
  title: string;
  questions: string[];
  custom?: boolean;
};

type LocalizedPack = {
  id: string;
  title: Record<Language, string>;
  questions: Record<Language, string[]>;
};

// Every built-in pack follows the same bilingual schema and stable ID.
const localizedPacks: LocalizedPack[] = [
  {
    id: 'standard',
    title: {
      de: 'Standard',
      en: 'Standard',
    },
    questions: {
      de: [
        'Serie',
        'Film',
        'Autor',
        'Bauwerk',
        'Werkzeug',
        'Kleidung',
        'Farbe',
        'Fach',
        'Möbelstück',
        'Gewächs',
        'Fast food',
        'Synonym für Geld',
        'Fluss',
        'Stadt im Inland',
        'Stadt im Ausland',
        'Land',
        'Name',
        'Weiblicher Name',
        'Männlicher Name',
        'Geschlechtsneutraler Name',
        'Ernährungsform',
        'Haustier',
        'In der Küche',
        'Im Schlafzimmer',
        'Im Wohnzimmer',
        'Bei den Großeltern',
        'Darf auf einer Reise nicht fehlen',
        'In der Handtasche',
        'Im Auto',
        'Im Weltall',
        'Auf dem Festival',
        'Kostüm',
        'So würde dein Museum heißen',
        'Trennungsgrund',
        'Macht attraktiv',
        'In einer Beziehung',
        'Hobby',
        'Essen',
        'Lebensmittel',
        'Im Kühlschrank',
        'Gesellschaftsspiel',
        'Videospiel',
        'Webseite',
        'Filmgenre',
        'Musikgenre',
        'Material',
        'Begriff rund um Computer',
        'Schiff',
        'Snack',
        'Musikinstrument',
        'Romanfigur',
        'Fest',
        'In einer Freundschaft',
        'Erfindung',
        'Gewürz',
        'Süßigkeit',
        'Spielzeug',
        'Kindheitsheld',
        'Beim Date',
        'Fantasyfigur',
        'Superheld',
        'Hat einen Griff',
        'Kinderlied',
        'Sprichwort',
        'Kommt in der Schulpause vor',
        'Körperteil',
        'Kleiner als ein Tennisball',
        'Besteht aus Metall',
        'Besteht aus Plastik',
        'Größer als ein Auto',
        'Wildes Tier',
        'Sportart',
        'Beruf',
        'Im Haushalt',
        'Verb',
        'Adjektiv',
        'Nomen',
        'In der Schule',
        'Sehenswürdigkeit',
        'Elektrogerät',
        'Im Baumarkt',
        'Stört bei der Arbeit',
        'Arbeitsunfall',
        'Stimmungskiller',
        'Biermarke',
        'Automarke',
        'Beim Raclette',
        'Im Zoo',
        'Sportler',
        'Wassertier',
        'Auf der Postkarte',
        'Eissorte',
        'Sportgerät',
        'Campingausrüstung',
        'Im Labor',
        'Drinnen',
        'Draußen',
        'Etwas aus einer erfundenen Welt',
        'Magischer Gegenstand aus einer Geschichte',
        'Begleiter in einer Abenteuergeschichte',
        'Etwas aus einem Weltraumabenteuer',
        'In der Zukunft',
        'Im Badezimmer',
        'Da möchte ich übernachten',
        'Zum Entspannen',
        'Getränk',
        'Ist kreativ',
        'Kann wachsen',
        'Kann schrumpfen',
        'leichter als 1kg',
        'schwerer als 10kg',
        'Gutes Versteck',
        'Gerät',
        'Braucht Strom',
        'Unter Wasser',
        'Aus der Physik',
        'Aus Biologie',
        'Etwas, das man mit seiner Heimat verbindet',
        'Buchtitel',
        'So würde mein Haustier heißen',
        'Im Handy',
        'Kuchen',
        'Pizzabelag',
        'Haushaltsaufgabe',
        'Davon mache ich Fotos',
        'Stört mich',
        'Mag ich',
        'Etwas, das ich gern bauen würde',
        'Beim wandern',
        'App',
        'Reiseziel',
        'Ein nettes Mitbringsel',
        'Eine gute Überraschung',
        'Typisch Büro',
        'Hat mehr als zwei Beine',
        'Hat Flügel',
        'Hat Klauen',
        'Hat Fell',
        'Hat Hufe',
        'Ist niedlich',
        'Ist hässlich',
        'Das wünsche ich mir',
        'Beim Arzt',
        'Tierbaby',
        'Im Schwimmbad',
        'Braucht man zum Putzen',
        'Teesorte',
        'In der Drogerie',
        'In der Welt will ich leben',
        'Im trend',
        'Stylisch',
        'Sternzeichen',
        'Etwas am Himmel',
        'Kosename',
        'Etwas, das man online anschaut',
        'An Weihnachten',
        'Bei einer Feier',
        'An einem freien Tag',
        'In einer Gemeinschaft',
        'Gibt Hoffnung',
        'Aus einer alten Erzählung',
        'Bei einer Übernachtung',
        'In der Nacht',
        'Im Internet',
        'Auf dem Flohmarkt',
        'Auf der Kirmes',
        'Nehme ich mit auf eine einsame Insel',
        'Braucht man zum Überleben',
        'Kann leuchten',
        'Glitzert',
        'In einer Bäckerei',
        'Auf dem Schminktisch',
        'Am Strand',
        'In der Politik',
        'Hier im Raum',
        'Auf dem Bauernhof',
        'Schauspieler',
        'Vogel',
        'Insekt',
        'Wetterlage',
        'Kinderserie',
        'So würde mein Film heißen',
        'So würde mein Buch heißen',
        'Klamottenmarke',
        'Markenname',
        'Kann man in der Mikrowelle kochen',
        'Rätselart',
        'Kompliment',
        'Das würde ich gerne erfinden',
        'Auf dem Wasser',
        'Die Person links von mir ist...',
        'Die Person rechts von mir ist...',
        'Ich bin...',
        'Etwas, das man gern verschenkt',
        'Etwas, das man ausleihen kann',
        'Passt in eine Hosentasche',
        'Etwas, das rollen kann',
        'Etwas, das weich ist',
        'Etwas, das gut riecht',
        'Etwas, das klebrig ist',
        'Etwas, das Geräusche macht',
        'Etwas, das man stapeln kann',
        'Etwas, das man teilen kann',
        'Etwas, das man sammelt',
        'Etwas, das man faltet',
        'Etwas, das man aufhängt',
        'Braucht man bei Regen',
        'Braucht man an einem heißen Tag',
        'Macht einen Raum gemütlich',
        'Etwas, das man feiern kann',
        'Eine kleine Überraschung',
        'Etwas für einen freien Nachmittag',
        'Etwas, das man ohne Geld machen kann',
        'Etwas, das man zusammen macht',
        'Etwas, das Geduld braucht',
        'Etwas, das man üben kann',
        'Ein ungewöhnliches Versteck',
        'Etwas, das man reparieren kann',
        'Etwas, das man im Park findet',
        'Etwas an einer Bushaltestelle',
        'Etwas, das man verpackt',
        'Etwas, das Freunde zum Lachen bringt',
        'Etwas, das den Tag schöner macht',
      ],
      en: [
        'TV series',
        'Movie',
        'Author',
        'Building',
        'Tool',
        'Item of clothing',
        'Color',
        'School subject',
        'Piece of furniture',
        'Plant',
        'Fast food',
        'Word for money',
        'River',
        'City in your country',
        'City abroad',
        'Country',
        'First name',
        'Female first name',
        'Male first name',
        'Gender-neutral first name',
        'Type of diet',
        'Pet',
        'In the kitchen',
        'In the bedroom',
        'In the living room',
        'At the grandparents house',
        'Must-have for a trip',
        'In a handbag',
        'In a car',
        'In outer space',
        'At a festival',
        'Costume',
        'Name for your museum',
        'Reason for a breakup',
        'Makes someone attractive',
        'In a relationship',
        'Hobby',
        'Meal',
        'Food',
        'In the fridge',
        'Board game',
        'Video game',
        'Website',
        'Movie genre',
        'Music genre',
        'Material',
        'A term about computers',
        'Ship',
        'Snack',
        'Musical instrument',
        'Novel character',
        'Celebration',
        'In a friendship',
        'Invention',
        'Spice',
        'Candy',
        'Toy',
        'Childhood hero',
        'On a date',
        'Fantasy character',
        'Superhero',
        'Has a handle',
        'Childrens song',
        'Proverb',
        'Something from a school break',
        'Body part',
        'Smaller than a tennis ball',
        'Made of metal',
        'Made of plastic',
        'Larger than a car',
        'Wild animal',
        'Sport',
        'Profession',
        'In the household',
        'Verb',
        'Adjective',
        'Noun',
        'At school',
        'Tourist attraction',
        'Electrical appliance',
        'At a hardware store',
        'Annoying at work',
        'Workplace accident',
        'Mood killer',
        'Beer brand',
        'Car brand',
        'At a dinner party',
        'At the zoo',
        'Athlete',
        'Aquatic animal',
        'On a postcard',
        'Ice cream flavor',
        'Sports equipment',
        'Camping gear',
        'In a laboratory',
        'Indoors',
        'Outdoors',
        'Something from an imaginary world',
        'A magical object from a story',
        'A companion in an adventure story',
        'Something from a space adventure',
        'In the future',
        'In the bathroom',
        'Place to spend the night',
        'For relaxing',
        'Drink',
        'Is creative',
        'Can grow',
        'Can shrink',
        'Lighter than one kilogram',
        'Heavier than ten kilograms',
        'Good hiding place',
        'Device',
        'Needs electricity',
        'Underwater',
        'From physics',
        'From biology',
        'Something associated with where you come from',
        'Book title',
        'Name for my pet',
        'On a phone',
        'Cake',
        'Pizza topping',
        'Household chore',
        'Something I photograph',
        'Annoys me',
        'Something I like',
        'Something I would like to build',
        'While hiking',
        'App',
        'Travel destination',
        'A thoughtful little gift',
        'A pleasant surprise',
        'Typical office item',
        'Has more than two legs',
        'Has wings',
        'Has claws',
        'Has fur',
        'Has hooves',
        'Is cute',
        'Is ugly',
        'Something I wish for',
        'At the doctors office',
        'Baby animal',
        'At a swimming pool',
        'Needed for cleaning',
        'Tea variety',
        'At a drugstore',
        'A world I would live in',
        'Trendy',
        'Stylish',
        'Zodiac sign',
        'Something in the sky',
        'Pet name',
        'Something you watch online',
        'At Christmas',
        'At a celebration',
        'On a day off',
        'In a community',
        'Gives people hope',
        'From an old tale',
        'At a sleepover',
        'At night',
        'On the internet',
        'At a flea market',
        'At a fairground',
        'Take to a desert island',
        'Needed for survival',
        'Can glow',
        'Sparkles',
        'In a bakery',
        'On a dressing table',
        'At the beach',
        'In politics',
        'In this room',
        'On a farm',
        'Actor',
        'Bird',
        'Insect',
        'Weather condition',
        'Childrens series',
        'Title of my movie',
        'Title of my book',
        'Clothing brand',
        'Brand name',
        'Microwaveable food',
        'Type of puzzle',
        'Compliment',
        'Something I would invent',
        'On the water',
        'The person to my left is …',
        'The person to my right is …',
        'I am …',
        'Something you like giving as a gift',
        'Something you can borrow',
        'Fits in a trouser pocket',
        'Something that can roll',
        'Something soft',
        'Something that smells nice',
        'Something sticky',
        'Something that makes a noise',
        'Something you can stack',
        'Something you can share',
        'Something people collect',
        'Something you fold',
        'Something you hang up',
        'Useful in the rain',
        'Useful on a hot day',
        'Makes a room cozy',
        'Something worth celebrating',
        'A little surprise',
        'Something for a free afternoon',
        'Something you can do without spending money',
        'Something you do together',
        'Something that takes patience',
        'Something you can practice',
        'An unusual hiding place',
        'Something you can repair',
        'Something found in a park',
        'Something at a bus stop',
        'Something you wrap up',
        'Something that makes friends laugh',
        'Something that makes the day better',
      ],
    },
  },
  {
    id: 'movies-tv',
    title: {
      de: 'Filme & Serien',
      en: 'Movies & TV',
    },
    questions: {
      de: [
        'Aus "Harry Potter"',
        'Aus "Herr der Ringe"',
        'Aus "Star Wars"',
        'Aus "Game of Thrones"',
        'Aus "Breaking Bad"',
        'Aus "The Walking Dead"',
        'Aus "The Big Bang Theory"',
        'Aus "The Simpsons"',
        'Aus "South Park"',
        'Aus "Spongebob"',
        'Aus "Family Guy"',
        'Aus "How I met your mother"',
        'Aus "Scrubs"',
        'Aus "Star Trek"',
        'Aus "The Office"',
        'Aus "Dune"',
        'Aus "The Witcher"',
        'Aus "The Mandalorian"',
        'Aus "The Boys"',
        'Aus dem Marvel Cinematic Universe',
        'Aus dem DC Extended Universe',
        'Figur mit einer besonderen Fähigkeit',
        'Aus "Dr. Who"',
        'Aus "Wednesday"',
        'Serie mit einer Reise ins Unbekannte',
        'Lustige Figur aus einer Serie',
        'Serie mit ungewöhnlichen Geschwistern',
        'Filmfigur mit einem Doppelleben',
        'Serie mit unheimlichen Begegnungen',
        'Aus "Stranger Things"',
        'Aus "Dr. House"',
        'Figur, die ein Geheimnis aufklärt',
        'Aus "Pokémon"',
        'Liebesfilm',
        'Actionfilm',
        'Horrorfilm',
        'Science-Fiction-Film',
        'Fantasyfilm',
        'Animationsfilm',
        'Dokumentarfilm',
        'Kriegsfilm',
        'Western',
        'Historienfilm',
        'Katastrophenfilm',
        'Märchenfilm',
        'Filmreihe',
        'Film mit Will Smith',
        'Film mit Tom Hanks',
        'Film mit Leonardo DiCaprio',
        'Film mit Johnny Depp',
        'Film mit Brad Pitt',
        'Film mit Robert Downey Jr.',
        'Film mit Dwayne Johnson',
        'Film mit Vin Diesel',
        'Film mit Arnold Schwarzenegger',
        'Film mit Sylvester Stallone',
        'Film mit Harrison Ford',
        'Film mit Bruce Willis',
        'Film mit Keanu Reeves',
        'Film mit Jackie Chan',
        'Film mit einer Zeitreise',
        'Serie mit einer Zeitreise',
        'Film, der im Weltall spielt',
        'Serie, die im Weltall spielt',
        'Film mit einem Roboter',
        'Film mit einem Drachen',
        'Film mit einem sprechenden Tier',
        'Film über eine Reise',
        'Film, der auf einem Buch basiert',
        'Serie, die auf einem Buch basiert',
        'Film mit einem unerwarteten Ende',
        'Film mit einer Verfolgungsjagd',
        'Film über einen Raubüberfall',
        'Film über Musik',
        'Film über Sport',
        'Film, der auf einer Insel spielt',
        'Film mit einem Monster',
        'Film mit einem Vampir',
        'Film mit einem Zombie',
        'Film mit einem Geist',
        'Film, der im Winter spielt',
        'Weihnachtsfilm',
        'Roadmovie',
        'Musicalfilm',
        'Thriller',
        'Kriminalfilm',
        'Spionagefilm',
        'Sportserie',
        'Krankenhausserie',
        'Krimiserie',
        'Sitcom',
        'Zeichentrickserie',
        'Anime-Serie',
        'Miniserie',
        'Serie mit einer erfundenen Stadt',
        'Serie über eine Familie',
        'Serie, die in einer Schule spielt',
        'Serie mit einem Detektiv',
        'Serie mit übernatürlichen Kräften',
        'Film mit einer weiblichen Hauptfigur',
        'Figur aus einem Pixar-Film',
        'Figur aus einem Disney-Film',
        'Figur aus einem Studio-Ghibli-Film',
        'Aus Avatar: Der Herr der Elemente',
        'Aus Friends',
        'Aus Brooklyn Nine-Nine',
        'Aus Sherlock',
        'Aus Buffy – Im Bann der Dämonen',
        'Aus Gilmore Girls',
        'Aus Lost',
        'Aus Futurama',
        'Aus Adventure Time',
        'Film oder Serie mit Geschwisterstreit',
        'Aus Dragon Ball',
        'Aus One Piece',
        'Film mit Meryl Streep',
        'Film mit Viola Davis',
        'Film mit Kate Winslet',
        'Film mit Natalie Portman',
        'Film mit Michelle Yeoh',
        'Gehört zu einem Kinoabend',
        'Gegenstand aus einer Filmszene',
        'Typischer Satz in einem Film',
        'Versteck für einen Filmschatz',
        'Ort für eine spannende Filmszene',
        'Etwas, das eine Filmfigur verliert',
        'Etwas, das eine Filmfigur retten muss',
        'Grund für Streit in einer Serie',
        'Film über Freundschaft',
        'Film mit einer Verwechslung',
        'Film über einen Wettbewerb',
        'Film mit einer Rettungsaktion',
        'Film, den man mehrmals anschauen kann',
        'Film oder Serie für einen Regentag',
        'Film oder Serie aus der Kindheit',
        'Film oder Serie, die gute Laune macht',
        'Etwas, das man auf einer Leinwand sieht',
        'Etwas im Gepäck einer Filmfigur',
        'Kleidung einer Filmfigur',
        'Beruf einer Serienfigur',
        'Tier als Begleiter einer Filmfigur',
        'Ein guter Titel für eine Komödie',
        'Ein guter Titel für einen Abenteuerfilm',
        'Name für ein erfundenes Fernsehstudio',
        'Panne bei Dreharbeiten',
        'Etwas, das man in einem Abspann liest',
        'Geräusch in einem Horrorfilm',
        'Etwas, das einen Bösewicht verrät',
        'Grund, warum eine Filmfigur umzieht',
        'Ungewöhnliches Ende für eine Liebesgeschichte',
      ],
      en: [
        'From Harry Potter',
        'From The Lord of the Rings',
        'From Star Wars',
        'From Game of Thrones',
        'From Breaking Bad',
        'From The Walking Dead',
        'From The Big Bang Theory',
        'From The Simpsons',
        'From South Park',
        'From SpongeBob SquarePants',
        'From Family Guy',
        'From How I Met Your Mother',
        'From Scrubs',
        'From Star Trek',
        'From The Office',
        'From Dune',
        'From The Witcher',
        'From The Mandalorian',
        'From The Boys',
        'From the Marvel Cinematic Universe',
        'From the DC universe',
        'A character with a special ability',
        'From Doctor Who',
        'From Wednesday',
        'A series with a journey into the unknown',
        'A funny character from a TV series',
        'A series with unusual siblings',
        'A movie character with a double life',
        'A series with spooky encounters',
        'From Stranger Things',
        'From House M.D.',
        'A character who solves a mystery',
        'From Pokémon',
        'Romance movie',
        'Action movie',
        'Horror movie',
        'Science-fiction movie',
        'Fantasy movie',
        'Animated movie',
        'Documentary',
        'War movie',
        'Western',
        'Historical movie',
        'Disaster movie',
        'Fairy-tale movie',
        'Movie franchise',
        'Movie starring Will Smith',
        'Movie starring Tom Hanks',
        'Movie starring Leonardo DiCaprio',
        'Movie starring Johnny Depp',
        'Movie starring Brad Pitt',
        'Movie starring Robert Downey Jr.',
        'Movie starring Dwayne Johnson',
        'Movie starring Vin Diesel',
        'Movie starring Arnold Schwarzenegger',
        'Movie starring Sylvester Stallone',
        'Movie starring Harrison Ford',
        'Movie starring Bruce Willis',
        'Movie starring Keanu Reeves',
        'Movie starring Jackie Chan',
        'Movie involving time travel',
        'TV series involving time travel',
        'Movie set in space',
        'TV series set in space',
        'Movie featuring a robot',
        'Movie featuring a dragon',
        'Movie featuring a talking animal',
        'Movie about a journey',
        'Movie based on a book',
        'TV series based on a book',
        'Movie with an unexpected ending',
        'Movie with a chase scene',
        'Heist movie',
        'Movie about music',
        'Movie about sports',
        'Movie set on an island',
        'Movie featuring a monster',
        'Movie featuring a vampire',
        'Movie featuring a zombie',
        'Movie featuring a ghost',
        'Movie set in winter',
        'Christmas movie',
        'Road movie',
        'Movie musical',
        'Thriller',
        'Crime movie',
        'Spy movie',
        'Sports series',
        'Medical drama series',
        'Crime series',
        'Sitcom',
        'Animated TV series',
        'Anime series',
        'Miniseries',
        'TV series with a fictional town',
        'TV series about a family',
        'TV series set in a school',
        'TV series featuring a detective',
        'TV series featuring supernatural powers',
        'Movie with a female protagonist',
        'Character from a Pixar movie',
        'Character from a Disney movie',
        'Character from a Studio Ghibli movie',
        'From Avatar: The Last Airbender',
        'From Friends',
        'From Brooklyn Nine-Nine',
        'From Sherlock',
        'From Buffy the Vampire Slayer',
        'From Gilmore Girls',
        'From Lost',
        'From Futurama',
        'From Adventure Time',
        'A movie or series with a sibling rivalry',
        'From Dragon Ball',
        'From One Piece',
        'Movie starring Meryl Streep',
        'Movie starring Viola Davis',
        'Movie starring Kate Winslet',
        'Movie starring Natalie Portman',
        'Movie starring Michelle Yeoh',
        'Part of a movie night',
        'An object in a movie scene',
        'A typical line in a movie',
        'A hiding place for a movie treasure',
        'A setting for an exciting movie scene',
        'Something a movie character loses',
        'Something a movie character must save',
        'A reason for an argument in a TV series',
        'A movie about friendship',
        'A movie with a case of mistaken identity',
        'A movie about a competition',
        'A movie with a rescue mission',
        'A movie worth watching more than once',
        'A movie or series for a rainy day',
        'A movie or series from childhood',
        'A movie or series that cheers you up',
        'Something you see on a cinema screen',
        'Something in a movie character’s luggage',
        'Clothing worn by a movie character',
        'A TV character’s job',
        'An animal companion for a movie character',
        'A good title for a comedy',
        'A good title for an adventure movie',
        'A name for an imaginary TV studio',
        'A mishap on a film set',
        'Something listed in the closing credits',
        'A sound in a horror movie',
        'Something that gives a villain away',
        'A reason a movie character moves house',
        'An unusual ending to a love story',
      ],
    },
  },
  {
    id: 'everyday-chaos',
    title: {de: 'Alltag & Chaos', en: 'Everyday & Chaos'},
    questions: {
      de: [
        'Grund fürs Zuspätkommen',
        'Liegt immer im Weg',
        'Geht montags kaputt',
        'Vergisst man beim Einkaufen',
        'Peinlicher Autokorrekturfehler',
        'Ausrede im Homeoffice',
        'Macht der Nachbar zu laut',
        'Verschwindet im Haushalt',
        'Findet man unter dem Sofa',
        'Schlechter Ort für einen Schlüssel',
        'Grund für Chaos in der Küche',
        'Unnötiger Onlinekauf',
        'Wird ständig verlegt',
        'Typischer WG-Streit',
        'Macht einen Morgen schlimmer',
        'Seltsamer Paketinhalt',
        'Steht seit Monaten auf der To-do-Liste',
        'Wird im Kühlschrank vergessen',
        'Unpassender Klingelton',
        'Dumme Verletzung',
        'Seltsamer Fund in der Jackentasche',
        'Grund für einen Stromausfall',
        'Spontane Wochenendidee',
        'Verdächtiges Geräusch nachts',
        'Muss dringend repariert werden',
        'Schlechtes Passwort',
        'Komischer WLAN-Name',
        'Grund, das Haus nicht zu verlassen',
        'Kleine Alltagskatastrophe',
        'Unnützes Küchengerät',
        'Verboten im Treppenhaus',
        'Tut man statt aufzuräumen',
        'Seltsame Erinnerung im Kalender',
        'Macht man nur aus Höflichkeit',
        'Darf niemand im Browserverlauf sehen',
        'Schlechte Idee vor dem Schlafengehen',
        'Grund für eine Beschwerde',
        'Merkwürdige Fundsache',
        'Wird viel zu lange aufgehoben',
        'Sollte man nicht in die Mikrowelle legen',
        'Wird vor einem Besuch schnell versteckt',
        'Kleine Freude am Morgen',
        'Hält einen vom Aufstehen ab',
        'Macht die Warteschlange länger',
        'Wird gern auf morgen verschoben',
        'Geht beim Umzug verloren',
        'Kann man sich beim Nachbarn leihen',
        'Landet versehentlich in der Wäsche',
        'Braucht man genau dann, wenn es fehlt',
        'Macht einen kurzen Einkauf lang',
        'Grund für eine vergessene Verabredung',
        'Wird beim Aufräumen wiedergefunden',
        'Wird in der Wohnung umgestellt',
        'Kommt auf einen Einkaufszettel',
        'Grund, den Wecker früher zu stellen',
        'Etwas, das einen Tag rettet',
        'Etwas, das man zu Hause nachfüllt',
        'Etwas, das man unterwegs vergisst',
        'Schlechter Platz für ein Getränk',
        'Kommt in die falsche Schublade',
        'Unangenehme Überraschung beim Putzen',
        'Grund für ein verschwundenes Paar Socken',
        'Etwas, das man ständig aufladen muss',
        'Wird beim Packen überschätzt',
        'Grund, noch einmal nach Hause zu gehen',
        'Etwas, das man am Telefon klärt',
        'Lässt sich mit Klebeband retten',
        'Etwas, das im Flur herumsteht',
        'Wird mit dem falschen Namen angesprochen',
        'Macht man während einer Wartezeit',
      ],
      en: [
        'Reason for being late',
        'Always in the way',
        'Breaks on a Monday',
        'Forgotten at the grocery store',
        'Embarrassing autocorrect fail',
        'Work-from-home excuse',
        'The neighbor does it too loudly',
        'Keeps disappearing at home',
        'Found under the sofa',
        'Bad place for a key',
        'Cause of chaos in the kitchen',
        'Unnecessary online purchase',
        'Constantly misplaced',
        'Typical roommate argument',
        'Makes a morning worse',
        'Strange parcel content',
        'On the to-do list for months',
        'Forgotten in the fridge',
        'Inappropriate ringtone',
        'Ridiculous injury',
        'Odd thing in a jacket pocket',
        'Cause of a power outage',
        'Spontaneous weekend idea',
        'Suspicious noise at night',
        'Needs urgent repair',
        'Bad password',
        'Weird Wi-Fi name',
        'Reason not to leave the house',
        'Tiny everyday disaster',
        'Useless kitchen gadget',
        'Banned in the stairwell',
        'Done instead of tidying up',
        'Strange calendar reminder',
        'Done only to be polite',
        'Should not appear in browser history',
        'Bad idea before bedtime',
        'Reason to complain',
        'Odd lost property',
        'Kept for far too long',
        'Should not go in a microwave',
        'Quickly hidden before visitors arrive',
        'A small morning joy',
        'Keeps you from getting out of bed',
        'Makes a queue take longer',
        'Often put off until tomorrow',
        'Lost when moving house',
        'Something you can borrow from a neighbor',
        'Accidentally ends up in the laundry',
        'Needed just when it goes missing',
        'Turns a quick shopping trip into a long one',
        'A reason for forgetting an appointment',
        'Rediscovered while tidying up',
        'Moved around at home',
        'Something on a shopping list',
        'A reason to set an earlier alarm',
        'Something that saves the day',
        'Something you refill at home',
        'Something you forget while out and about',
        'A bad place to put a drink',
        'Ends up in the wrong drawer',
        'An unpleasant surprise while cleaning',
        'A reason a pair of socks disappears',
        'Something that constantly needs charging',
        'Something you overestimate when packing',
        'A reason to go back home',
        'Something you sort out over the phone',
        'Can be rescued with tape',
        'Something left standing in the hallway',
        'Called by the wrong name',
        'Something you do while waiting',
      ],
    },
  },
  {
    id: 'fantasy-rpg',
    title: {de: 'Fantasy & Rollenspiel', en: 'Fantasy & Role-playing'},
    questions: {
      de: [
        'Fantasywesen',
        'Magischer Gegenstand',
        'Name einer Taverne',
        'Zauberspruch',
        'Drachenname',
        'Grund für eine Quest',
        'Fundstück im Dungeon',
        'Rolle in einer Abenteurergruppe',
        'Fantasyberuf',
        'Name eines Königreichs',
        'Fluch',
        'Segen einer Gottheit',
        'Monsterfähigkeit',
        'Zutat für einen Trank',
        'Falle im Dungeon',
        'Gerücht in der Taverne',
        'Name einer Abenteurergruppe',
        'Makel eines Helden',
        'Schatz eines Drachen',
        'Magie, die man lieber verbieten würde',
        'Gottheit',
        'Gruseliges Wesen',
        'Grund für einen Pakt',
        'Fähigkeit eines Artefakts',
        'Begegnung im Wald',
        'Peinliches Lied in einer Taverne',
        'Problem einer tapferen Heldin oder eines Helden',
        'Ausrede eines Diebes',
        'Eigenart eines Zauberers',
        'Name eines Dungeons',
        'Währung einer Fantasywelt',
        'Transportmittel in einer Fantasywelt',
        'Begleiter eines Helden',
        'Etwas in der Tasche eines Goblins',
        'Titel eines finsteren Herrschers',
        'Prophezeiung',
        'Grund für ein gescheitertes Abenteuer',
        'Versteck eines getarnten Monsters',
        'Belohnung für eine Nebenquest',
        'Regel in einer Magierakademie',
        'Etwas in der Küche einer Hexe',
        'Geschenk für einen Drachen',
        'Grund, warum ein Zauber schiefgeht',
        'Etwas hinter einer geheimen Tür',
        'Etwas, das ein Riese verliert',
        'Etwas im Garten eines Zauberers',
        'Etwas, das ein verwunschener Spiegel zeigt',
        'Ungewöhnliches Reittier',
        'Ausrede eines müden Drachen',
        'Etwas, das ein Schloss bewacht',
        'Etwas im Gepäck eines Abenteurers',
        'Geräusch in einem verzauberten Wald',
        'Magischer Helfer im Haushalt',
        'Nebenwirkung eines Zaubertranks',
        'Etwas, das eine Fee sammelt',
        'Ein Wunsch an eine gute Fee',
        'Etwas, das ein Monster fürchtet',
        'Grund für einen Streit im Königshaus',
        'Etwas auf einem königlichen Fest',
        'Ungewöhnliches Haustier im Schloss',
        'Etwas, das eine Schatzkarte verrät',
        'Ein Verbot in einem Feenreich',
        'Etwas, das man unsichtbar machen möchte',
        'Ein magisch verändertes Kleidungsstück',
        'Ein Problem mit einem fliegenden Teppich',
        'Name für einen sprechenden Baum',
        'Etwas im Laden für Zauberbedarf',
        'Etwas, das einen Fluch aufheben könnte',
        'Ein Geheimnis einer alten Burg',
        'Etwas, das am Ende eines Abenteuers wartet',
      ],
      en: [
        'Fantasy creature',
        'Magic item',
        'Tavern name',
        'Spell',
        'Dragon name',
        'Reason for a quest',
        'Found in a dungeon',
        'A role in an adventuring group',
        'Fantasy profession',
        'Kingdom name',
        'Curse',
        'Blessing from a deity',
        'Monster ability',
        'Potion ingredient',
        'Dungeon trap',
        'Tavern rumor',
        'Adventuring party name',
        'Heroic flaw',
        'Part of a dragon’s hoard',
        'Magic you would rather ban',
        'Deity',
        'A spooky creature',
        'Reason for a pact',
        'Artifact ability',
        'Forest encounter',
        'An embarrassing tavern song',
        'A problem for a brave hero',
        'A thief’s excuse',
        'Wizard’s odd habit',
        'Dungeon name',
        'Fantasy currency',
        'Fantasy mode of transport',
        'Hero’s companion',
        'In a goblin’s pocket',
        'Title of a dark ruler',
        'Prophecy',
        'A reason an adventure fails',
        'A hiding place for a disguised monster',
        'Side-quest reward',
        'Rule at a magic academy',
        'Something in a witch’s kitchen',
        'A gift for a dragon',
        'A reason a spell goes wrong',
        'Something behind a secret door',
        'Something a giant loses',
        'Something in a wizard’s garden',
        'Something an enchanted mirror shows',
        'An unusual animal to ride',
        'A tired dragon’s excuse',
        'Something that guards a castle',
        'Something in an adventurer’s luggage',
        'A sound in an enchanted forest',
        'A magical helper around the house',
        'A potion’s side effect',
        'Something a fairy collects',
        'A wish for a fairy godmother',
        'Something a monster fears',
        'A reason for an argument in a royal family',
        'Something at a royal feast',
        'An unusual castle pet',
        'Something a treasure map reveals',
        'Something forbidden in a fairy kingdom',
        'Something you would make invisible',
        'A magically altered item of clothing',
        'A problem with a flying carpet',
        'A name for a talking tree',
        'Something in a magic supply shop',
        'Something that could break a curse',
        'An old castle’s secret',
        'Something waiting at the end of an adventure',
      ],
    },
  },
  {
    id: 'gaming-nerd',
    title: {de: 'Gaming & Nerdkultur', en: 'Gaming & Nerd Culture'},
    questions: {
      de: [
        'Videospielcharakter',
        'Spielekonsole',
        'Bossgegner',
        'Indie-Spiel',
        'Gaming-Genre',
        'Grund für einen Ragequit',
        'Item in einer Lootbox',
        'Name eines Clans',
        'NPC-Spruch',
        'Schlechtes Achievement',
        'Übermächtige Fähigkeit',
        'Abkürzung in einem Spiel',
        'Retro-Spiel',
        'Etwas, das man in einem Brettspiel macht',
        'Science-Fiction-Technologie',
        'Robotername',
        'Superkraft mit Nachteil',
        'Etwas, das ein Computer können sollte',
        'Programm, das den Alltag erleichtert',
        'Begriff aus der digitalen Welt',
        'Fehlermeldung',
        'Grund für Serverausfall',
        'Teil eines Gaming-PCs',
        'Spielfigur',
        'Sammelkartenspiel',
        'Name eines Raumschiffs',
        'Alien-Spezies',
        'Problem bei einer Zeitreise',
        'Convention-Kostüm',
        'Fan-Theorie',
        'Völlig unnötiges Gadget',
        'KI mit schlechtem Namen',
        'Hacker-Alias',
        'Name eines Endgegners',
        'Trick für ein Spiel',
        'Ding auf dem Schreibtisch',
        'Etwas, das man in einem Spiel sammeln kann',
        'Etwas, das eine Spielfigur tragen kann',
        'Ein Hindernis in einem Spiel',
        'Etwas, das man in einem Spiel bauen kann',
        'Ein Ort für ein neues Spiel',
        'Etwas, das man beim Spielen sucht',
        'Etwas für einen Spieleabend',
        'Eine Regel für ein erfundenes Spiel',
        'Ein erfundener Spieltitel',
        'Eine Belohnung im Spiel',
        'Grund für eine Spielpause',
        'Etwas, das ein Roboter lernen sollte',
        'Etwas, das ein Roboter falsch versteht',
        'Eine Fähigkeit für einen Superhelden',
        'Ein Name für eine Superheldengruppe',
        'Ein Problem auf einem Raumschiff',
        'Etwas, das ein Alien mit nach Hause nimmt',
        'Ein Ort für eine versteckte Belohnung',
        'Ein lustiger Name für eine Spielfigur',
        'Etwas, das man einem Team zuruft',
        'Ein Gerät aus der Zukunft',
        'Etwas, das ein Gerät automatisch machen könnte',
        'Ein Problem mit einer App',
        'Eine nützliche Handyfunktion',
        'Etwas, das man digital verschickt',
        'Ein Zubehör für einen Computer',
        'Ein Gegner mit einer albernen Schwäche',
        'Etwas, das man in einem Spiel beschützen muss',
        'Ein Grund für einen überraschenden Sieg',
        'Etwas, das ein Spiel schwieriger macht',
      ],
      en: [
        'Video game character',
        'Game console',
        'Boss enemy',
        'Indie game',
        'Game genre',
        'Reason for a rage quit',
        'Loot-box item',
        'Clan name',
        'NPC catchphrase',
        'Bad achievement',
        'Overpowered ability',
        'A shortcut in a game',
        'Retro game',
        'Something you do in a board game',
        'Science-fiction technology',
        'Robot name',
        'Superpower with a downside',
        'Something a computer should be able to do',
        'A program that makes everyday life easier',
        'A term from the digital world',
        'Error message',
        'Reason for a server outage',
        'Part of a gaming PC',
        'A game piece',
        'Trading card game',
        'Spaceship name',
        'Alien species',
        'A problem with time travel',
        'Convention costume',
        'Fan theory',
        'Completely unnecessary gadget',
        'Badly named AI',
        'Hacker alias',
        'Final boss name',
        'A trick for a game',
        'On the desk',
        'Something you can collect in a game',
        'Something a game character can wear',
        'An obstacle in a game',
        'Something you can build in a game',
        'A setting for a new game',
        'Something you look for in a game',
        'Something for a game night',
        'A rule for an invented game',
        'An invented game title',
        'An in-game reward',
        'A reason to take a gaming break',
        'Something a robot should learn',
        'Something a robot misunderstands',
        'An ability for a superhero',
        'A name for a superhero team',
        'A problem on a spaceship',
        'Something an alien takes home',
        'A place for a hidden reward',
        'A funny name for a game character',
        'Something you shout to a team',
        'A device from the future',
        'Something a device could do automatically',
        'A problem with an app',
        'A useful phone feature',
        'Something you send digitally',
        'A computer accessory',
        'An enemy with a silly weakness',
        'Something you must protect in a game',
        'A reason for an unexpected win',
        'Something that makes a game harder',
      ],
    },
  },
  {
    id: 'party-dark-humor',
    title: {de: 'Party & schwarzer Humor', en: 'Party & Dark Humor'},
    questions: {
      de: [
        'Schlechter Grund anzustoßen',
        'Peinlicher Party-Moment',
        'Kater-Ausrede',
        'Warnschild auf einer WG-Party',
        'Grund für Hausverbot',
        'Seltsamer Cocktailname',
        'Was man beim ersten Date verschweigt',
        'Unpassendes Hochzeitsgeschenk',
        'Letzte Worte vor einer schlechten Idee',
        'Grund für einen Notruf',
        'Tattoo, das man bereut',
        'Schlechter Name für ein Bestattungsunternehmen',
        'Unangebrachtes Beerdigungslied',
        'Miese Grabinschrift',
        'Verdächtiges Alibi',
        'Grund, aus einer Bar zu fliegen',
        'Etwas im Flachmann',
        'Partyspiel mit Verletzungsgefahr',
        'Schlimmer Mitternachtssnack',
        'Grund für eine Familienfehde',
        'Darf nicht in die Gruppenchat-Historie',
        'Unpassender Trinkspruch',
        'Schrecklicher Junggesellenabschied',
        'Grund für eine spontane Flucht',
        'Was nach „Halt mal mein Bier“ passiert',
        'Kreative Beleidigung',
        'Ding, das auf einer Party brennt',
        'Schlechter Ort zum Aufwachen',
        'Grund für eine toxische Bewertung',
        'Party-Motto mit Warnsignal',
        'Wird am nächsten Morgen geleugnet',
        'Schlechtes Geschenk vom Ex',
        'Dumme Mutprobe',
        'Grund für eine sehr kurze Karriere',
        'Unnötig dramatischer Abgang',
        'Name einer Metalband',
        'Morbider Kosename',
        'Ausrede gegenüber der Polizei',
        'Etwas, das Oma nicht hören sollte',
        'Grund, sofort nüchtern zu werden',
        'Ein Gast, den niemand eingeladen hat',
        'Etwas, das eine Party unerwartet beendet',
        'Ein albernes Motto für eine Feier',
        'Etwas, das man vor den Gästen versteckt',
        'Ein Geschenk mit zweifelhafter Botschaft',
        'Ein schlechter Satz in einer Festrede',
        'Eine Ausrede für einen vergessenen Geburtstag',
        'Etwas, das auf einem Gruppenfoto schiefgeht',
        'Ein Grund für peinliche Stille',
        'Etwas, das man lieber nur denkt',
        'Ein unpassender Moment zum Lachen',
        'Ein schlechter Name für ein Krankenhaus',
        'Eine Beschwerde eines Geistes',
        'Etwas, das einem Vampir den Abend verdirbt',
        'Ein Problem bei einem Zombie-Treffen',
        'Eine peinliche Nachricht an die falsche Person',
        'Ein seltsamer Fund nach einer Feier',
        'Etwas, das eine Überraschung verrät',
        'Ein Grund für einen misslungenen Überraschungsbesuch',
        'Eine schlechte Idee für ein Partyfoto',
        'Ein unpassendes Geschenk für den Chef',
        'Etwas, das man auf einer Feier verwechselt',
        'Eine schlechte Ausrede für ein kaputtes Sofa',
        'Ein Grund für eine verdächtig leere Tanzfläche',
        'Ein Warnsignal bei einem selbst gemixten Getränk',
        'Eine schlechte Überschrift für die Party des Jahres',
        'Ein seltsamer Programmpunkt bei einer Hochzeit',
        'Etwas, das ein Skelett vermisst',
        'Ein schlechter Werbespruch für einen Friedhof',
        'Ein Grund, eine Geschichte lieber nicht zu erzählen',
      ],
      en: [
        'Bad reason for a toast',
        'Embarrassing party moment',
        'Hangover excuse',
        'Warning sign at a house party',
        'Reason for a venue ban',
        'Weird cocktail name',
        'Hidden on a first date',
        'Inappropriate wedding present',
        'Last words before a bad idea',
        'Reason for an emergency call',
        'Regrettable tattoo',
        'Bad name for a funeral home',
        'Inappropriate funeral song',
        'Terrible epitaph',
        'Suspicious alibi',
        'Reason for being thrown out of a bar',
        'Inside a hip flask',
        'Party game with injury risk',
        'Awful midnight snack',
        'Reason for a family feud',
        'Must not remain in the group-chat history',
        'Inappropriate toast',
        'Disastrous bachelor party',
        'Reason for a sudden escape',
        'What follows “hold my beer”',
        'Creative insult',
        'On fire at a party',
        'Bad place to wake up',
        'Reason for a one-star review',
        'Party theme with red flags',
        'Denied the next morning',
        'Bad present from an ex',
        'Stupid dare',
        'Reason for a very short career',
        'Needlessly dramatic exit',
        'Metal band name',
        'Morbid pet name',
        'Excuse given to the police',
        'Grandma should not hear this',
        'Reason to become sober instantly',
        'A guest nobody invited',
        'Something that unexpectedly ends a party',
        'A silly theme for a celebration',
        'Something hidden from the guests',
        'A gift with a questionable message',
        'A bad line in a celebration speech',
        'An excuse for forgetting a birthday',
        'Something that goes wrong in a group photo',
        'A reason for an awkward silence',
        'Something you would rather keep to yourself',
        'An inappropriate moment to laugh',
        'A bad name for a hospital',
        'A ghost’s complaint',
        'Something that ruins a vampire’s evening',
        'A problem at a zombie gathering',
        'An embarrassing message sent to the wrong person',
        'An odd discovery after a celebration',
        'Something that gives away a surprise',
        'A reason a surprise visit goes wrong',
        'A bad idea for a party photo',
        'An inappropriate gift for the boss',
        'Something mixed up at a celebration',
        'A bad excuse for a broken sofa',
        'A reason for a suspiciously empty dance floor',
        'A warning sign in a homemade drink',
        'A bad headline for the party of the year',
        'An odd activity at a wedding',
        'Something a skeleton misses',
        'A bad advertising slogan for a cemetery',
        'A reason to keep a story to yourself',
      ],
    },
  },
  {
    id: 'nature-animals',
    title: {de: 'Natur & Tiere', en: 'Nature & Animals'},
    questions: {
      de: [
        'Säugetier',
        'Vogelart',
        'Reptil',
        'Tier in und am Wasser',
        'Insekt',
        'Meerestier',
        'Nachtaktives Tier',
        'Giftiges Tier',
        'Ausgestorbenes Tier',
        'Tier mit Tarnung',
        'Zugvogel',
        'Bestäuber',
        'Tier mit einer besonderen Fähigkeit',
        'Lebensraum',
        'Baumart',
        'Pflanze, die man im Alltag nutzt',
        'Giftpflanze',
        'Pilzart',
        'Gestein',
        'Mineral',
        'Wetterphänomen',
        'Naturkatastrophe',
        'Ort, an dem viele Tiere leben',
        'Ort mit viel Natur',
        'Gebirgszug',
        'Flusslandschaft',
        'Spur eines Tieres',
        'Tierlaut',
        'Überlebensstrategie',
        'Tiere oder Pflanzen, die einander helfen',
        'Etwas, das sich schnell verbreitet',
        'Bedrohte Art',
        'Fossil',
        'Dinosaurier',
        'Pflanze für den Garten',
        'Etwas im Kompost',
        'Fundstück am Strand',
        'Tier mit ungewöhnlichem Namen',
        'Naturphänomen am Nachthimmel',
        'Ein Tier, das klettern kann',
        'Ein Tier, das hüpft',
        'Ein Tier, das im Boden lebt',
        'Ein Tier, das man im Garten sieht',
        'Ein Tier, das Vorräte sammelt',
        'Ein Tier mit einem langen Schwanz',
        'Ein Tier mit einem Panzer',
        'Ein Tier, das man hören kann',
        'Etwas, das im Herbst vom Baum fällt',
        'Etwas, das im Frühling wächst',
        'Etwas, das man im Wald riecht',
        'Etwas am Rand eines Sees',
        'Etwas, das an einem Baum wächst',
        'Etwas, das eine Pflanze braucht',
        'Etwas, das der Wind bewegt',
        'Etwas, das man im Schnee findet',
        'Ein Unterschlupf für ein Tier',
        'Ein Tier, das in einer Gruppe lebt',
        'Etwas, das Tiere fressen',
        'Etwas, das man auf einer Wiese findet',
        'Eine Pflanze mit Blüten',
        'Etwas, das auf der Wasseroberfläche schwimmt',
        'Ein natürlicher Schutz vor Regen',
        'Etwas, das im Sommer summt',
        'Etwas, das man bei einem Spaziergang beobachtet',
        'Etwas, das nach einem Gewitter zu sehen ist',
        'Ein Tier, das langsam unterwegs ist',
        'Ein Tier, das schnell unterwegs ist',
        'Etwas, das in einer Pfütze lebt',
        'Etwas, das die Natur bunt macht',
      ],
      en: [
        'Mammal',
        'Bird species',
        'Reptile',
        'An animal in or near water',
        'Insect',
        'Marine animal',
        'Nocturnal animal',
        'Venomous animal',
        'Extinct animal',
        'Animal with camouflage',
        'Migratory bird',
        'Pollinator',
        'An animal with a special ability',
        'Habitat',
        'Tree species',
        'A plant used in everyday life',
        'Poisonous plant',
        'Fungus',
        'Rock',
        'Mineral',
        'Weather phenomenon',
        'Natural disaster',
        'A place where many animals live',
        'A place with lots of nature',
        'Mountain range',
        'River landscape',
        'Animal track',
        'Animal sound',
        'Survival strategy',
        'Animals or plants that help each other',
        'Something that spreads quickly',
        'Endangered species',
        'Fossil',
        'Dinosaur',
        'Garden plant',
        'In a compost heap',
        'Found on a beach',
        'Animal with an unusual name',
        'Natural phenomenon in the night sky',
        'An animal that can climb',
        'An animal that hops',
        'An animal that lives underground',
        'An animal you see in a garden',
        'An animal that stores food',
        'An animal with a long tail',
        'An animal with a shell',
        'An animal you can hear',
        'Something that falls from a tree in autumn',
        'Something that grows in spring',
        'Something you smell in a forest',
        'Something at the edge of a lake',
        'Something that grows on a tree',
        'Something a plant needs',
        'Something moved by the wind',
        'Something found in the snow',
        'A shelter for an animal',
        'An animal that lives in a group',
        'Something animals eat',
        'Something found in a meadow',
        'A plant with flowers',
        'Something floating on the water',
        'A natural shelter from the rain',
        'Something that buzzes in summer',
        'Something you notice on a walk',
        'Something seen after a thunderstorm',
        'An animal that moves slowly',
        'An animal that moves quickly',
        'Something that lives in a puddle',
        'Something that makes nature colorful',
      ],
    },
  },
  {
    id: 'knowledge-science',
    title: {de: 'Wissen & Wissenschaft', en: 'Knowledge & Science'},
    questions: {
      de: [
        'Physikalische Einheit',
        'Chemisches Element',
        'Etwas, das sehr klein ist',
        'Laborgerät',
        'Naturgesetz',
        'Teilchen',
        'Säure',
        'Stoff, den man zum Reinigen benutzt',
        'Metall',
        'Ein Gas, das man kennt',
        'Organ des Menschen',
        'Knochen',
        'Reaktion des Körpers',
        'Krankheitserreger',
        'Eine Ähnlichkeit in der Familie',
        'Frage, die die Forschung beantworten soll',
        'Mathematischer Begriff',
        'Geometrische Form',
        'Etwas, das man zählt',
        'Astronomisches Objekt',
        'Sternbild',
        'Etwas für eine Weltraumreise',
        'Entdecker oder Erfinder',
        'Wissenschaftlerin',
        'Messinstrument',
        'Energiequelle',
        'Materialeigenschaft',
        'Etwas, das sich bei Wärme verändert',
        'Optisches Phänomen',
        'Eigenschaft, die einem Tier hilft',
        'Etwas aus früheren Zeiten',
        'Archäologischer Fund',
        'Etwas, worüber man lange nachdenken kann',
        'Etwas, das unsere Stimmung verändert',
        'Begriff aus der Welt des Geldes',
        'Sprache mit besonderer Schrift',
        'Entdeckung, die für viele Menschen wichtig ist',
        'Experiment für die Schule',
        'Etwas, das schwimmen kann',
        'Etwas, das Wärme erzeugt',
        'Etwas, das Geräusche verstärkt',
        'Etwas, das man mit einer Lupe untersucht',
        'Etwas, das man wiegen kann',
        'Etwas, das man messen kann',
        'Etwas, das Licht braucht',
        'Etwas, das einen Schatten wirft',
        'Etwas, das sich dreht',
        'Etwas, das durch Wasser verändert wird',
        'Etwas, das gefrieren kann',
        'Etwas, das verdampfen kann',
        'Etwas, das Strom leitet',
        'Etwas, das man am Körper messen kann',
        'Ein Hilfsmittel zum Lernen',
        'Etwas, das man unter einem Mikroskop sieht',
        'Etwas, das Rost bekommen kann',
        'Etwas, das man recyceln kann',
        'Ein Gegenstand mit einem Magneten',
        'Ein Material aus dem Alltag',
        'Etwas, das eine Maschine antreibt',
        'Etwas, das beim Backen chemisch verändert wird',
        'Ein Zeichen für einen Wetterwechsel',
        'Etwas, das Menschen erforschen',
        'Etwas, das man auf einer Karte einzeichnet',
        'Etwas, das man bei einem Experiment braucht',
        'Etwas, das schneller als ein Mensch ist',
        'Etwas, das Energie spart',
        'Etwas, das man nur mit einem Hilfsmittel sieht',
        'Eine Erfindung, die den Alltag erleichtert',
      ],
      en: [
        'Physical unit',
        'Chemical element',
        'Something very small',
        'Laboratory equipment',
        'Law of physics',
        'Particle',
        'Acid',
        'A substance used for cleaning',
        'Metal',
        'A gas you know',
        'Human organ',
        'Bone',
        'A reaction of the body',
        'Pathogen',
        'A family resemblance',
        'A question for scientists to answer',
        'Mathematical term',
        'Geometric shape',
        'Something you count',
        'Astronomical object',
        'Constellation',
        'Something for a space journey',
        'Explorer or inventor',
        'Female scientist',
        'Measuring instrument',
        'Energy source',
        'Material property',
        'Something that changes when heated',
        'Optical phenomenon',
        'A trait that helps an animal',
        'Something from the past',
        'Archaeological discovery',
        'Something you could think about for a long time',
        'Something that changes our mood',
        'A term about money',
        'Language with a distinctive script',
        'A discovery that matters to many people',
        'School science experiment',
        'Something that can float',
        'Something that produces heat',
        'Something that makes sounds louder',
        'Something you examine with a magnifying glass',
        'Something you can weigh',
        'Something you can measure',
        'Something that needs light',
        'Something that casts a shadow',
        'Something that spins',
        'Something changed by water',
        'Something that can freeze',
        'Something that can evaporate',
        'Something that conducts electricity',
        'Something you can measure on the body',
        'A tool for learning',
        'Something seen under a microscope',
        'Something that can rust',
        'Something you can recycle',
        'An object containing a magnet',
        'An everyday material',
        'Something that powers a machine',
        'Something chemically changed by baking',
        'A sign that the weather is changing',
        'Something people study',
        'Something marked on a map',
        'Something needed for an experiment',
        'Something faster than a person',
        'Something that saves energy',
        'Something you need a tool to see',
        'An invention that makes everyday life easier',
      ],
    },
  },
  {
    id: 'food-drinks',
    title: {de: 'Essen & Getränke', en: 'Food & Drinks'},
    questions: {
      de: [
        'Gemüsesorte',
        'Obstsorte',
        'Hülsenfrucht',
        'Käsesorte',
        'Brotsorte',
        'Nudelgericht',
        'Reisgericht',
        'Suppe',
        'Salat',
        'Dessert',
        'Kuchen',
        'Gebäck',
        'Gewürz',
        'Kräuter',
        'Soße',
        'Dip',
        'Streetfood',
        'Vegetarisches Gericht',
        'Vegane Zutat',
        'Lebensmittel, das lange haltbar ist',
        'Frühstück',
        'Mitternachtssnack',
        'Picknick-Essen',
        'Party-Snack',
        'Eissorte',
        'Pizzabelag',
        'Zutat im Curry',
        'Etwas vom Grill',
        'Heißgetränk',
        'Erfrischungsgetränk',
        'Cocktail',
        'Mocktail',
        'Biersorte',
        'Etwas aus einem Getränkeladen',
        'Seltsame Geschmackskombination',
        'Gericht mit lustigem Namen',
        'Ein erfundenes Gericht',
        'Kulinarisches Souvenir',
        'Etwas Knuspriges',
        'Etwas, das niemals auf Pizza gehört',
        'Etwas Süßes zum Frühstück',
        'Etwas Herzhaftes zum Frühstück',
        'Etwas, das man auf Brot streicht',
        'Etwas, das man mit den Händen isst',
        'Etwas, das man schält',
        'Etwas, das man vor dem Essen wäscht',
        'Etwas, das man einfrieren kann',
        'Etwas, das man in einer Pfanne brät',
        'Etwas, das man in einem Topf kocht',
        'Etwas, das im Backofen zubereitet wird',
        'Etwas mit einer knackigen Schale',
        'Etwas, das beim Kochen gut duftet',
        'Etwas Saures',
        'Etwas Scharfes',
        'Etwas Salziges',
        'Etwas für eine Lunchbox',
        'Etwas auf einem Frühstücksbuffet',
        'Etwas für eine große Runde Gäste',
        'Etwas zum Essen unterwegs',
        'Etwas, das man mit Gästen teilt',
        'Etwas, das man dekorieren kann',
        'Ein Belag für ein Sandwich',
        'Ein Getränk für einen kalten Abend',
        'Ein Getränk mit Früchten',
        'Etwas, das man in ein Glas füllt',
        'Etwas für eine heiße Schokolade',
        'Etwas, das ein Gericht bunter macht',
        'Etwas, das man am Kiosk kauft',
        'Etwas, das als Rest noch gut schmeckt',
        'Ein Essen für einen gemütlichen Abend',
      ],
      en: [
        'Vegetable',
        'Fruit',
        'Legume',
        'Cheese',
        'Type of bread',
        'Pasta dish',
        'Rice dish',
        'Soup',
        'Salad',
        'Dessert',
        'Cake',
        'Pastry',
        'Spice',
        'Herb',
        'Sauce',
        'Dip',
        'Street food',
        'Vegetarian dish',
        'Vegan ingredient',
        'A food that keeps for a long time',
        'Breakfast food',
        'Midnight snack',
        'Picnic food',
        'Party snack',
        'Ice cream flavor',
        'Pizza topping',
        'Curry ingredient',
        'Something from a barbecue',
        'Hot drink',
        'Soft drink',
        'Cocktail',
        'Mocktail',
        'Type of beer',
        'Something from a drinks shop',
        'Odd flavor combination',
        'Dish with a funny name',
        'An invented dish',
        'Culinary souvenir',
        'Something crunchy',
        'Something that never belongs on pizza',
        'Something sweet for breakfast',
        'Something savory for breakfast',
        'Something you spread on bread',
        'Something you eat with your hands',
        'Something you peel',
        'Something you wash before eating',
        'Something you can freeze for later',
        'Something you fry in a pan',
        'Something you cook in a pot',
        'Something made in an oven',
        'Something with a crunchy shell',
        'Something that smells nice while cooking',
        'Something sour',
        'Something spicy',
        'Something salty',
        'Something for a lunch box',
        'Something on a breakfast buffet',
        'Something to serve a large group of guests',
        'Something to eat on the go',
        'Something you share with guests',
        'A food you can decorate',
        'A sandwich filling',
        'A drink for a cold evening',
        'A drink with fruit',
        'Something you put in a glass',
        'Something to add to hot chocolate',
        'Something that adds color to a dish',
        'Something bought at a snack stand',
        'Something that tastes good as leftovers',
        'A meal for a cozy evening',
      ],
    },
  },
  {
    id: 'travel-places',
    title: {de: 'Reisen & Orte', en: 'Travel & Places'},
    questions: {
      de: [
        'Hauptstadt',
        'Insel',
        'Gebirge',
        'Ort am Meer',
        'Stadt für ein Wochenende',
        'Reiseziel im Winter',
        'Reiseziel im Sommer',
        'Ort für Sternenbeobachtung',
        'Sehenswürdigkeit',
        'Museum',
        'Burg oder Schloss',
        'Verkehrsmittel',
        'Ding im Handgepäck',
        'Wird am Bahnhof ausgerufen',
        'Flughafenproblem',
        'Typisches Souvenir',
        'Kulinarisches Reiseziel',
        'Ort mit Vulkanen',
        'Ort im Regenwald',
        'Ort in der Wüste',
        'Ort, an dem es sehr kalt ist',
        'Historische Stadt',
        'Fiktiver Urlaubsort',
        'Roadtrip-Stopp',
        'Ungewöhnliche Unterkunft',
        'Grund für eine Grenzkontrolle',
        'Satz aus einem Sprachführer',
        'Reisepanne',
        'Urlaubsaktivität',
        'Wanderziel',
        'Ort für eine Zeitreise',
        'Stadt mit berühmter Architektur',
        'Land, das du gern besuchen würdest',
        'Ort mit besonderem Nachtleben',
        'Reiseziel ohne Auto',
        'Ort für eine Expedition',
        'Etwas, das in einen Koffer gehört',
        'Etwas, das man vor einer Reise erledigt',
        'Etwas für eine lange Zugfahrt',
        'Etwas, das man in einem Hotel findet',
        'Etwas, das man auf einer Reise fotografiert',
        'Etwas für einen Tag am See',
        'Etwas, das man an einer Raststätte sieht',
        'Etwas, das man auf einer Landkarte sucht',
        'Ein Ort für ein Picknick',
        'Ein Ort für einen Ausflug mit Freunden',
        'Ein Ort zum Abkühlen',
        'Ein Ort, an dem man gut lesen kann',
        'Ein Ort, den man zu Fuß erreicht',
        'Etwas, das auf einen Campingplatz gehört',
        'Etwas, das man in einer fremden Stadt sucht',
        'Ein Grund für einen Umweg',
        'Ein Geräusch am Bahnhof',
        'Etwas auf einem Straßenschild',
        'Etwas, das man in einem Reisebüro fragt',
        'Ein Grund, eine Reise zu verlängern',
        'Etwas, das einen Urlaub gemütlich macht',
        'Etwas, das man nur im Urlaub macht',
        'Ein Ort für einen Regentag',
        'Etwas, das man in einem Besucherzentrum findet',
        'Ein Mitbringsel für jemanden zu Hause',
        'Etwas, das man auf einem Stadtplan erkennt',
        'Ein Ort für eine kleine Pause',
        'Etwas für einen Tagesausflug',
        'Etwas, das man bei der Ankunft zuerst macht',
        'Ein Ort, an dem man neue Leute kennenlernt',
      ],
      en: [
        'Capital city',
        'Island',
        'Mountain range',
        'Place by the sea',
        'City for a weekend',
        'Winter destination',
        'Summer destination',
        'Place for stargazing',
        'Tourist attraction',
        'Museum',
        'Castle or palace',
        'Mode of transport',
        'In carry-on luggage',
        'Announced at a train station',
        'Airport problem',
        'Typical souvenir',
        'Culinary destination',
        'Place with volcanoes',
        'Place in a rainforest',
        'Place in a desert',
        'A very cold place',
        'Historic city',
        'Fictional holiday destination',
        'Road-trip stop',
        'Unusual accommodation',
        'Reason for a border check',
        'Phrasebook sentence',
        'Travel mishap',
        'Holiday activity',
        'Hiking destination',
        'Place for time travel',
        'City with famous architecture',
        'A country you would like to visit',
        'Place with special nightlife',
        'Car-free destination',
        'Place for an expedition',
        'Something that belongs in a suitcase',
        'Something you do before a trip',
        'Something for a long train journey',
        'Something found in a hotel',
        'Something you photograph on a trip',
        'Something for a day at the lake',
        'Something seen at a rest stop',
        'Something you look for on a map',
        'A place for a picnic',
        'A place to visit with friends',
        'A place to cool down',
        'A good place to read',
        'A place you can reach on foot',
        'Something that belongs on a campsite',
        'Something you look for in an unfamiliar city',
        'A reason to take a detour',
        'A sound at a train station',
        'Something on a road sign',
        'Something you ask at a travel agency',
        'A reason to extend a trip',
        'Something that makes a holiday relaxing',
        'Something you only do on holiday',
        'A place to visit on a rainy day',
        'Something found in a visitor center',
        'A gift for someone back home',
        'Something you recognize on a city map',
        'A place for a short break',
        'Something for a day trip',
        'Something you do first on arrival',
        'A place to meet new people',
      ],
    },
  },
];

export const getBuiltInQuestionPacks = (language: Language): QuestionPack[] =>
  localizedPacks.map(pack => ({
    id: pack.id,
    title: pack.title[language],
    questions: [...pack.questions[language]],
  }));

export const builtInPackIds = localizedPacks.map(pack => pack.id);
